### ISSUE TITLE
Enabling SCIM UserOperationListener for SCIM 1.1

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#1000]
Location : https://is.docs.wso2.com/en/5.9.0/develop/scim-1.1-apis/
By default `SCIM2 UserOperationListener` is enabled but when using SCIM 1.1 the `SCIM UserOperationListener` should be explicitly enabled.
<img width="1078" alt="Screen Shot 2019-12-19 at 3 12 57 PM" src="https://user-images.githubusercontent.com/525801/71217274-11e41d80-2272-11ea-8856-59d60c3cd747.png">

**Comment by gomathyk** [comment]
We cannot enable both scim 1.1 and scim2 at a given time. If the user needs to work on scim 1.1, he needs to disable scim2 and enable scim 1.1. scim2 is enabled by default because scim1.1 is deprecated and not recommended.
