### ISSUE TITLE
The document should be updated accordingly latest FIDO api changes

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#1003]
Affected: 5.10 documents
The document should be updated accordingly latest FIDO API changes 
and should add brief description of the API.
document: WSO2 Identity Server FIDO 2 Rest API[1]
[1] https://is.docs.wso2.com/en/next/develop/fido-rest-api/

**Comment by dewniMW** [comment]
Same issue reported at https://github.com/wso2/docs-is/issues/917

**Comment by dewniMW** [comment]
This document has been added to IS doc space [1].

[1] https://is.docs.wso2.com/en/latest/develop/fido-rest-api/
