### ISSUE TITLE
Misconfiguration when configuring Duo Security Provisioning Connector

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/docs-is#1031]
In the doc [1] - "Configuring the identity provider" section - Step 4 "Click Add Claim Mapping and add the following claims."
Username local claim URI needs to be changed as "**http://wso2.org/claims/givenname**". 

We do not keep the username in the "http://wso2.org/claims/username" due to that, DUO getting null value.

[1] - https://docs.wso2.com/display/ISCONNECTORS/Configuring+Duo+Security+Provisioning+Connector#ConfiguringDuoSecurityProvisioningConnector-Configuringtheidentityprovider

**Comment by gomathyk** [comment]
https://docs.wso2.com/display/ISCONNECTORS/Configuring+Duo+Security+Provisioning+Connector has been modified now addressing the issue.
