### ISSUE TITLE
[Doc] Outdated SCIM2 document

### ISSUE THREAD

**Issue by rksk** [wso2/docs-is#1063]
Since the SCIM2 connector is packaged OOTB with newer Identity Server versions, the following two sections are not required.

- Deploy SCIM 2.0 connector with IS
- Configure claim dialects

However, please keep the "Extending the SCIM API" section since it is useful to add custom claims.

https://is.docs.wso2.com/en/5.9.0/develop/scim-2.0-provisioning-connector/

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/1076.

Now the SCIM 2.0 documentation is available at https://is.docs.wso2.com/en/5.9.0/develop/scim-2.0-provisioning/

**Comment by sherenewso2** [comment]
This content is now at https://is.docs.wso2.com/en/5.9.0/develop/extending-scim2-user-schemas/
