### ISSUE TITLE
[Doc] Incorrect Callback Url format in 'Configuring Google' doc

### ISSUE THREAD

**Issue by rksk** [wso2/docs-is#1064]
The doc says Callback Url format should be `https://(host-name):(port)/acs`. Ideally, it should be `https://(host-name):(port)/commonauth`. 

Affected all the versions except 5.1.0

https://is.docs.wso2.com/en/next/learn/configuring-google/
https://is.docs.wso2.com/en/5.9.0/learn/configuring-google/
https://docs.wso2.com/display/IS580/Configuring+Google
https://docs.wso2.com/display/IS570/Configuring+Google
https://docs.wso2.com/display/IS560/Configuring+Google
https://docs.wso2.com/display/IS550/Configuring+Google
https://docs.wso2.com/display/IS541/Configuring+Google
https://docs.wso2.com/display/IS540/Configuring+Google
https://docs.wso2.com/display/IS530/Configuring+Google
https://docs.wso2.com/display/IS520/Configuring+Google

**Comment by rksk** [comment]
@sherenewso2 The latest doc also has to be updated

https://is.docs.wso2.com/en/next/learn/configuring-google/

**Comment by gomathyk** [comment]
This has already been updated in https://is.docs.wso2.com/en/next/learn/configuring-google/.
