### ISSUE TITLE
Changing top nav order of documentation 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#107]
Current order highlights compliance before the others. 
![Screen Shot 2019-08-31 at 9 54 32 AM](https://user-images.githubusercontent.com/54733286/64059371-f2e55100-cbd8-11e9-98fb-b82b652e18d1.png)
Suggestion to reorder as follows

Getting Started 
Using WSO2 Identity Server (option 2: move after setup)
Setup 
Tutorials 
Connectors  
Admin Guide
Compliance 
References

**Comment by gomathyk** [comment]
Will be modified with https://github.com/wso2/docs-is/pull/870
