### ISSUE TITLE
Docs need to be update based on https://github.com/wso2/product-is/issues/6925

### ISSUE THREAD

**Issue by Kanapriya** [wso2/docs-is#1072]
**Description:**
In the latest WUM updated pack of IS 5.7.0, 5.9.0 and in master (5.10.0), we have introduced ACS URL in the federated SAML flow as an IdP level config which allows having different ACS URL with each federated IdP.

<img width="1615" alt="Screen Shot 2020-01-21 at 3 42 19 PM" src="https://user-images.githubusercontent.com/13362482/72796288-16cb3100-3c65-11ea-9f8e-96d22ac0368c.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-is/issues/6925

**Comment by YvonneW** [comment]
https://github.com/wso2/docs-is/pull/1098 will fix this.

**Comment by Kanapriya** [comment]
This fix is available only in 5.7.0 and 5.9.0
