### ISSUE TITLE
Some edit links are not working

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/docs-is#110]
**Description:**
There is and issue with the edit links. I suspect that the doc compiler is making the URLs to lowercase and the file names are maintaining with non-lower case causing the issue.

_**Solution:** Make all the file names lowercase._

Ex:-

Edit link on: 
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc/

----

Redirect file path name (Broken):
https://github.com/wso2/docs-is/edit/master/en/docs/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc.md

Actual file path name:
https://github.com/wso2/docs-is/edit/master/en/docs/using-wso2-identity-server/private-Key-JWT-Client-Authentication-for-OIDC.md

**Comment by sherenewso2** [comment]
This has been fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/176
