### ISSUE TITLE
Consider moving "Product Administration" out of "Using WSO2 Identity Server"

### ISSUE THREAD

**Issue by pulasthi7** [wso2/docs-is#112]
Most of the topics under "Product Administraion" which is currently under "Using WSO2 Identity Server" are related to "Setup" or "Admin Guide". Consider moving them appropriately and highlight the feature documentation under "Using WSO2 Identity Server"

**Comment by gomathyk** [comment]
The deployment and migration content in product administration have been moved to setup section and the remaining pages have moved to administer section now. 

https://is.docs.wso2.com/en/5.9.0/setup/migration-process/
https://is.docs.wso2.com/en/5.9.0/administer/configuring-the-identity-server/
