### ISSUE TITLE
User-store configurations doesn't include by-default configurations

### ISSUE THREAD

**Issue by denuwanthi** [wso2/docs-is#1144]
**Description:**
Related to https://github.com/wso2/product-is/issues/7464
user store configurations for unique-id based user stores are not documented.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sherenewso2** [comment]
This has been addressed in [1]

[1] https://is.docs.wso2.com/en/5.11.0/setup/migrating-what-has-changed/#new-user-store-managers-with-built-in-unique-id-support
