### ISSUE TITLE
Need to mention that old userstore manager implementations are deprectaed in 5.10.0 

### ISSUE THREAD

**Issue by denuwanthi** [wso2/docs-is#1145]
**Description:**
Use of old user store managers like "org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager" should not be used with 5.10.0 onwards. 
Instead UniqueID based userstore implementations should be used.
The migration client will add the migration from old implementation to new one when migrating from an older product version.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sherenewso2** [comment]
This has been addressed in [1] 

[1] https://is.docs.wso2.com/en/5.11.0/setup/migrating-what-has-changed/#new-user-store-managers-with-built-in-unique-id-support
