### ISSUE TITLE
[Docs] [Improvement] Should MFA with FIDO say Webauthn explicitly on the title? 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#115]
Since WebAuthn will be a highlight of 5.9, can we explicitly mention that as a subheading here [1]? 
Suggestion: Define Webauthn if possible or link article. 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/multi-factor-authentication-using-fido/

**Comment by ayshsandu** [comment]
Removed in the latest https://is.docs.wso2.com/en/5.9.0/learn/multi-factor-authentication-using-fido/
