### ISSUE TITLE
Doc handling internal scopes in migration doc

### ISSUE THREAD

**Issue by janakamarasena** [wso2/docs-is#1150]
Currently, by default, internal scopes will be enabled in a migrated setup, but this will break existing applications using some APIs such as scim2/Me.

We can go back to the previous behaviour and disable scope based permissions with the following config in the deployment.toml file.

```
[resource_access_control]
disable_scope_validation=true
```

Ref:https://github.com/wso2/product-is/issues/7536

**Comment by Abilashini** [comment]
documented at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#handling-internal-scopes
