### ISSUE TITLE
Link under OAuth 1.0 is broken 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#120]
Under [1], page linked to "This specification" is broken
[1]https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/oauth-concepts/#oauth-10

![Screen Shot 2019-08-31 at 11 50 15 AM](https://user-images.githubusercontent.com/54733286/64060530-99d2e880-cbeb-11e9-9b34-1697a289bf09.png)

**Comment by isharanaotunna** [comment]
https://github.com/wso2/product-is/issues/6268

**Comment by deshankoswatte** [comment]
Hi @isharanaotunna,

This is fixed in [1] as mentioned at the below screen record. Hence closing this issue.

![Peek 2019-11-24 22-06](https://user-images.githubusercontent.com/33062368/69497787-c2c2fb00-0f06-11ea-8fbc-31225c688d7d.gif)

[1] - https://is.docs.wso2.com/en/5.9.0/learn/oauth-concepts/
