### ISSUE TITLE
Broken links under "Using APIs" 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#122]
Same issue as the developer guide page, all links under using APIs [1] are 404

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-APIs/

**Comment by deshankoswatte** [comment]
Hi @isharanaotunna,

All the links under the page[1] works. Hence closing this issue.

[1] - https://is.docs.wso2.com/en/5.9.0/develop/using-apis/

**Comment by gomathyk** [comment]
This is corrected now with the restructured sections 
https://is.docs.wso2.com/en/5.9.0/develop/using-apis/.
