### ISSUE TITLE
Outdated Documentation : Configuring Instagram Authenticator

### ISSUE THREAD

**Issue by DinikaSen** [wso2/docs-is#1222]
**Description:**
The Instagram federated authenticator cannot be used as Instagram API Platform is no longer available. The [https://docs.wso2.com/display/ISCONNECTORS/Configuring+Instagram+Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Instagram+Authenticator) doc needs to be revised accordingly.

**Related Issues:**
[https://github.com/wso2/product-is/issues/7648](https://github.com/wso2/product-is/issues/7648)

**Comment by ashendes** [comment]
Working on this.
