### ISSUE TITLE
Issues in the UMA endpoints doc

### ISSUE THREAD

**Issue by Abilashini** [wso2/docs-is#1223]
Link to the doc: https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/

1. Update a resource description(https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/#updating-a-resource-description) request contains 'HTTP/1.1' repeated 2 times. 

2. Listing resource descriptions(https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/#listing-a-resource-descriptions) 
The title should be corrected as 'LISTING RESOURCE DESCRIPTIONS'

3. Listing resource descriptions(https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/#listing-a-resource-descriptions) request contains repeated 'Authorization' header

4. Permission endpoint (https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/#permission-endpoint) - sample request and response related to the given diagram are not documented.

**Comment by AnuradhaSK** [comment]
I'm working on this
