### ISSUE TITLE
Doc Feedback: IS 5.9.0 misspelled parameters for saml_sso_authenticator

### ISSUE THREAD

**Issue by dengrand** [wso2/docs-is#1235]
Hi,

There is an error in the following documentation.

Location : https://is.docs.wso2.com/en/5.9.0/learn/enabling-sso-for-management-console-using-opensso-as-the-idp/

In the part "Setting up the WSO2 product", there is a parameter misspelled (an 'r' is missing and it's not in the correct case).
"ServiceProvideID" should be "service_provider_id".

I think the same applies to the following two (but I didn't try to modify those).
"IdentityProviderSSOServiceURL" and "idpCertAlias" should be in lower case with '_' separation.

Best Regards

**Comment by piraveena** [comment]
Hi @dengrand ,

Thanks for reporting the issue. 

As you mentioned, it should be as given below


```
[admin_console.authenticator.saml_sso_authenticator]
service_provider_id = ""    
identity_provider_sso_service_url = ""
idp_cert_alias = ""
```


**service_provider_id** represents ServiceProviderID 
**identity_provider_sso_service_url** represents IdentityProviderSSOServiceURL
**idp_cert_alias** represents IdPCertAlias

We will fix this issue.
