### ISSUE TITLE
Images are outdated (in 5.10 docs)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#1236]
**Description:**
Images should be updated, it describes with dashboard examples, should be explained with user portal from 5.10
Identity Server Documentation WIPPassword Recovery[1]

[1]https://is.docs.wso2.com/en/next/learn/password-recovery/#recovery-using-challenge-questions

**Comment by GANGANI** [comment]
i'm working on this

**Comment by DinikaSen** [comment]
Working on this
