### ISSUE TITLE
Broken link in the connectors page 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#124]
Link: "Creating a Third Party Authenticator or Connector and Publishing in WSO2 Store" is broken. Directs to a 404 

![Screen Shot 2019-08-31 at 12 55 12 PM](https://user-images.githubusercontent.com/54733286/64060749-99881c80-cbee-11e9-9c9b-3ee80ee3f39e.png)

**Comment by gomathyk** [comment]
Closing issue since the connector docs have been removed for now.
