### ISSUE TITLE
Information missing on what is ACR and AMR

### ISSUE THREAD

**Issue by mefarazath** [wso2/docs-is#126]
Check https://docs.wso2.com/display/IS570/Working+with+ACR+and+AMR. This doc contains what is ACR and AMR before guiding the user to try out the scenario.

But the doc at https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-acr-based-adaptive-authentication/ seems to be missing this information.

**Comment by ayshsandu** [comment]
https://is.docs.wso2.com/en/5.9.0/learn/working-with-acr-and-amr/ document contains the necessary information.
