### ISSUE TITLE
Include a link to download SOAP UI

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/docs-is#128]
**Description:**
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-roles-and-permissions/#add-role-using-soap
Better if some link is provided in the doc to download the SOAP UI for testing SOAP services.

![Screenshot from 2019-08-31 13-04-59](https://user-images.githubusercontent.com/51709964/64060844-0cde5e00-cbf0-11e9-9c62-27cbeb794215.png)

**Suggested Labels:**
Type Improvement

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/880
