### ISSUE TITLE
Remove message body for 401 and 403 responses in server apis swagger doc

### ISSUE THREAD

**Issue by Thumimku** [wso2/docs-is#1281]
**Description:**
Need to remove message body of 401, 403 responses for server rest APIs regarding this update. https://github.com/wso2/identity-api-server/pull/106

**Comment by Thumimku** [comment]
we need to address this PR update as well.
[Remove message body for 401 and 403 responses in user apis](https://github.com/wso2/identity-api-user/pull/86)

**Comment by DinikaSen** [comment]
Working on this
