### ISSUE TITLE
[Improvement] Difference between admin guide and product administration under using WSO2 IS? 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#129]
Can these be grouped together or do they serve two different purposes? If not can the product admin section [1]in using wso2 be combined with the admin guide or included under it?  

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/product-Administration/
[2] https://is.docs.wso2.com/en/5.9.0/admin-guide/wSO2-Administration-Guide/

**Comment by gomathyk** [comment]
This structure has changed now. 

WSO2 administration guide was more of a reference guide consisting of the configurations commonly used for all WSO2 products and product administration had configurations specific to Identity Server. 

Now we have the product administration and other admin content relevant to IS here -  https://is.docs.wso2.com/en/5.9.0/administer/wso2-administration-guide/.
