### ISSUE TITLE
Content missing in "Invoke the OAuth Introspection Endpoint"

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/docs-is#130]
**Description:**
Only client_credential grant type has explained. Need to point to other grant types as well. 

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/invoke-the-oauth-introspection-endpoint/

**Comment by ayshsandu** [comment]
Added a note mentioning invoking introspect endpoint for other grants are also same as client-credentials grant in the https://github.com/wso2/docs-is/pull/900
