### ISSUE TITLE
Authorization code request has not explained properly

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/docs-is#131]
**Description:**

Need to explain properly how to get the authorization code. How to construct the URL etc ...

`https://<host>/oauth2/authorize?response_type=code&client_id=<client-key>&redirect_uri=<callback-url>&scope=<?scope>`

Also need to explain how to construct curl for each grant types

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/try-authorization-code-grant/

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/913
