### ISSUE TITLE
Doc Feedback: No configuration to add the database url

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/docs-is#1323]
When using the toml configurations from the following [1] location, a warning is occurred as the following screenshot.
![image](https://user-images.githubusercontent.com/19262008/75652496-32bcec00-5c81-11ea-9c06-de547317effc.png)
To avoid that, the database url must contain useSSL=true/false param. But in the following [1] there is no any configuration to add the database url.
[1] Location : https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/#changing-the-default-datasource

**Comment by ashendes** [comment]
Working on this.
