### ISSUE TITLE
Broken page "using-the-SCIM-2.0-REST-APIs"

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/docs-is#133]
**Description:**
Content and links are broken in this page. Need to fix it or remove it.

Found this page from a google search

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-the-SCIM-2.0-REST-APIs/

![image](https://user-images.githubusercontent.com/7569427/64062583-ceec3480-cc05-11e9-8c24-052824f4ced8.png)

**Comment by ayshsandu** [comment]
Removed and the correct doc is at https://is.docs.wso2.com/en/5.9.0/develop/using-the-scim-2.0-rest-apis/
