### ISSUE TITLE
[Doc] An end to end sample is not available to demonstrate the purpose of Outbound Provisioning Connectors

### ISSUE THREAD

**Issue by pubudup** [wso2/docs-is#1340]
A sample with actual usage should be provided for Outbound Provisioning Connectors. The documentation describes how to configure IS but doesn't show the usage, therefore, the document has less value. If we provide a sample with what's the purpose of this configuration then it will be more useful.

https://docs.wso2.com/display/IS530/Configuring+Outbound+Provisioning+Connectors+for+an+Identity+Provider

**Comment by sherenewso2** [comment]
There are now end-to-end tutorials for outbound provisioning like [1] therefore closing this issue.

[1] https://is.docs.wso2.com/en/latest/learn/outbound-provisioning-with-salesforce/
