### ISSUE TITLE
[Doc] Broken links in some pages

### ISSUE THREAD

**Issue by ayshsandu** [wso2/docs-is#1341]
[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-Provisioning/#inbound-provisioning
Following links redirects to page not found
![provisioning](https://user-images.githubusercontent.com/5061791/64059459-b7e41d00-cbda-11e9-8f75-19fb44d02220.png)

**Comment by GANGANI** [comment]
All the above mentioned issues with broken links were fixed in the latest 5.10 documentation.
