### ISSUE TITLE
Add details on missing root CA from the Java certificate store

### ISSUE THREAD

**Issue by kasundharmadasa** [wso2/docs-is#1343]
Maven build fails with the error ***One or more certificates rejected. Cannot proceed with installation***. To fix this we need to import the GTE CyberTrust Global Root to the Java certificate store. The required steps needs to be added to the Readme.md as in product-ei [1].

[1] https://github.com/wso2/product-ei

**Comment by ruwanta** [comment]
This is not related to product. It is general issue in build environment when someone want to build with not-tested JDK.
-1 to add anything to the product doc as this generic issue and the solutions are known over the internet.
