### ISSUE TITLE
Sample for "SAML2 Bearer Assertion Profile for OAuth 2.0 with WSO2 Travelocity" is missing in the new docs

### ISSUE THREAD

**Issue by gayashanbc** [wso2/docs-is#135]
Sample[1] for "SAML2 Bearer Assertion Profile for OAuth 2.0 with WSO2 Travelocity" is missing in the new docs

[1] https://docs.wso2.com/display/IS530/SAML2+Bearer+Assertion+Profile+for+OAuth+2.0+with+WSO2+Travelocity

**Comment by gayashanbc** [comment]
### Update 
Flow does not work for tenants if the audience and recipient URLs are configured as per Step 3 in old docs[1].

### Current config in the doc

> If you have configured the service provider in a tenant, you have to add the tenant domain as a query parameter to the access token endpoint. If the tenant domain is wso2.com, enter the following values:

```
Audience : https://localhost:9443/oauth2/token?tenantDomain=wso2.com
Recipient : https://localhost:9443/oauth2/token?tenantDomain=wso2.com
```

### Should be updated to

> If you have configured the service provider in a tenant, you have to add the tenant domain as a query parameter to the access token endpoint. If the tenant domain is wso2.com, enter the following values:

```
Audience : https://localhost:9443/oauth2/token
Recipient : https://localhost:9443/oauth2/token
```

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
