### ISSUE TITLE
[doc] schema documents for identity.xml and axis2.xml

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/docs-is#1356]
Are there any schema documents available for Identity Server's XML configuration files?  This will be a significant help for file-based configurations.

**Comment by ruwanta** [comment]
We are moving all the configurations on to the "deplpyment.toml" file. Modifying independent XML files is deprecated going forward from 5.9.0.
The most updated config catalogue available in CSV format at,
https://github.com/wso2/identity-tools/blob/master/components/config-model-migrator/resources/catalog.csv

**Comment by sherenewso2** [comment]
Closing this issue as the configs have been moved to the deployment.toml file from IS 5.9.0 onwards
