### ISSUE TITLE
Missing information when configuring carbon remote userstore manager

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#137]
When configuring a remote IS as a carbon remote userstore manager, it is required to import the remote server's public certificate to primary IS's <IS_HOME>/repository/resources/security/client-trustore.jks file. We need to capture this requirement in the docs.

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/carbon-Remote-User-Store-Manager/

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/913
