### ISSUE TITLE
Elaborate on the configuring of SOAP UI console.

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/docs-is#138]
**Description:**
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-users/#creating-new-users-using-soap
Include details as to how the username,password and domain has to be configured in the SOAP UI console under  Authorization and security related settings.

![Screenshot from 2019-08-31 15-29-56](https://user-images.githubusercontent.com/51709964/64062462-373a1680-cc04-11e9-8e2c-50f508ff7032.png)

**Suggested Labels:**
Type Improvement

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/configuring-users/
