### ISSUE TITLE
Configuration is defined for "xml" file

### ISSUE THREAD

**Issue by ayeshajay** [wso2/docs-is#139]
https://is.docs.wso2.com/en/5.9.0/tutorials/querying-SAML-Assertions/

![Screenshot from 2019-08-31 15-30-49](https://user-images.githubusercontent.com/51480027/64062481-62bd0100-cc04-11e9-822a-7c5171baed54.png)

**Comment by janakamarasena** [comment]
in the following page as well there are configurations defined for xml

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc/

**Comment by ayshsandu** [comment]
Fixed in https://is.docs.wso2.com/en/5.9.0/learn/private-key-jwt-client-authentication-for-oidc/ and https://is.docs.wso2.com/en/5.9.0/learn/querying-saml-assertions/
