### ISSUE TITLE
Broken Pages "openID-Connect-*"

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/docs-is#140]
**Description:**
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Single-Logout
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Logout-URL-Redirection/

![image](https://user-images.githubusercontent.com/7569427/64062565-93516a80-cc05-11e9-86f1-e28818f1d66d.png)

**Comment by sherenewso2** [comment]
This has been fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/194
