### ISSUE TITLE
Titles of the PATCH and PUT endpoints of SCIM need to be corrected

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/docs-is#142]
**Description:**
Titles of the PATCH and PUT endpoints of SCIM need to be corrected as follows.

- `PATCH/ UPDATE USER` [1] should be corrected as `PATCH/ UPDATE GROUP`
- `PUT/ UPDATE USER`[2] should be corrected as `PUT/ UPDATE GROUP`

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/18381642/64062592-e7f4e580-cc05-11e9-8c56-f65108f73768.png">

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/18381642/64062599-02c75a00-cc06-11e9-9330-7d67687b5f46.png">

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-the-SCIM-2.0-REST-APIs/#patch-update-user_1
[2] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-the-SCIM-2.0-REST-APIs/#put-update-user_1

**Suggested Labels:**
Priority/High
Type/Doc
Type/Bug
Complexity/Low
Affected/5.9.0-Alpha

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
