### ISSUE TITLE
Error with the response on SOAP UI after adding a role/user successfully.

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/docs-is#143]
**Description:**
When adding a role or user using SOAP services, the WSO2 management console displays the amendments successfully but no response is displayed in SOAP UI console.
![Screenshot from 2019-08-31 15-44-34](https://user-images.githubusercontent.com/51709964/64062624-402be780-cc06-11e9-82ba-24b12d324faf.png)

**Suggested Labels:**
Type Bug

**OS, DB, other environment details and versions:**    
OS- ubuntu
DB- POSTGRESS
Environment- 3

**Related Issues:**

**Comment by ayshsandu** [comment]
This is because no response body is sent back in the response. If you look at the "Raw" tab of the response window, you can see the proper Headers for the success response.
