### ISSUE TITLE
Invalid content in Password Grant docs

### ISSUE THREAD

**Issue by mefarazath** [wso2/docs-is#144]
Check https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/try-password-grant/

It contains an Info note,

> If you have configured the service provider in a tenant, you have to add the tenant domain as a query parameter to the access token endpoint.
> 
> If the tenant domain is wso2.com, access token endpoint will be as follows.
> 
> Access Token Endpoint: https://localhost:9443/oauth2/token?tenantDomain=wso2.com

This is not correct. Even if you have configured the service provider in a tenant you can simply call the token endpoint as https://localhost:9443/oauth2/token. It is not required to send the tenantDomain as a query parameter.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/913
