### ISSUE TITLE
Misleading to H2 database

### ISSUE THREAD

**Issue by ayeshajay** [wso2/docs-is#145]
https://is.docs.wso2.com/en/5.9.0/tutorials/querying-SAML-Assertions/

![Screenshot from 2019-08-31 16-37-01](https://user-images.githubusercontent.com/51480027/64063120-ac5e1980-cc0d-11e9-9eb2-4a2c03d72405.png)

**Comment by ayshsandu** [comment]
Addressed in https://github.com/wso2/docs-is/pull/927.
Now, https://is.docs.wso2.com/en/5.9.0/learn/querying-saml-assertions/ doesn't contain any database related configurations.
