### ISSUE TITLE
[Bug] Unrelated content inside "Configuring Twitter" section.

### ISSUE THREAD

**Issue by brionmario** [wso2/docs-is#149]
"Configuring a resident identity provider" instructions are mixed in with the "Configuring Twitter" section in the tutorials [1].

[1] https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-twitter/#configuring-twitter

<img width="1496" alt="Screen Shot 2019-08-31 at 5 02 58 PM" src="https://user-images.githubusercontent.com/25959096/64063378-4a9fae80-cc11-11e9-9961-c18fcfaefd2e.png">

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/913
