### ISSUE TITLE
Unaligned code samples - SCIM1 samples

### ISSUE THREAD

**Issue by ayshsandu** [wso2/docs-is#150]
Half the command is not visible to user.

The icon to copy the sample command is unaligned.

![Untitled document](https://user-images.githubusercontent.com/5061791/64066468-ada43c00-cc37-11e9-988f-2db907175133.png)

**Comment by ayshsandu** [comment]
This needs to be fixed in the theme

**Comment by gomathyk** [comment]
This is resolved with https://github.com/wso2/docs-is/pull/1061
