### ISSUE TITLE
Using Email Address as the Username documentation has deprecated configs.

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/docs-is#152]
**Description:**
Documentation[1] step 4 is asking to change some configurations in identity-mgt.properties file which is deprecated. We need to add the relevant new configurations here.

[1] - https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-email-address-as-the-username/

**Suggested Labels:**

- Priority/High
-  Type/Docs
- 5.9.0-Alpha

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/994/
