### ISSUE TITLE
Adding certificate option is not updated in the diagram 

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/docs-is#153]
**Description:**
Documentation[1] step 4 has an old diagram to show the adding certificate option for an Identity Provider. This diagram should be changed as shown below. 

<img width="915" alt="Screen Shot 2019-09-01 at 9 30 37 AM" src="https://user-images.githubusercontent.com/17598367/64071615-a3b42480-cc9b-11e9-80f6-046860302f70.png">

[1] - https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/outbound-provisioning-with-salesforce/

**Suggested Labels:**
- Priority/High
- Type/Doc
- 5.9.0-Alpha

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
