### ISSUE TITLE
Add more information to test Private Key JWT Client Authentication for OIDC easily

### ISSUE THREAD

**Issue by janakamarasena** [wso2/docs-is#154]
**Description:**
Add information to easily test the flow. The following details can be added.

https://medium.com/@hasinthaindrajee/private-key-jwt-client-authentication-for-oidc-1c496bbf221f

doc: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc/

**Comment by ayshsandu** [comment]
Will be addressed in https://github.com/wso2/docs-is/issues/429
