### ISSUE TITLE
Incorrect headings for patch group and patch user

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#155]
In SCIM2 rest API doc, under Groups endpoint, the headings for p**atch User** and **update User** should be changed to **patch Group** and **Update group**

![image](https://user-images.githubusercontent.com/8380730/64072175-eb40ad80-cca7-11e9-955c-f34507af79e5.png)

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-the-SCIM-2.0-REST-APIs/#groups-endpoint

**Comment by ayshsandu** [comment]
Same as https://github.com/wso2/docs-is/issues/142, fixed in https://github.com/wso2/docs-is/pull/900
