### ISSUE TITLE
Scrolling through the page conflicts with Topics Menu in the Left

### ISSUE THREAD

**Issue by darshanasbg** [wso2/docs-is#158]
Scroll down to the bottom of the page,
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Single-Logout/

The left menu get disappear.

And scrolling up again appear the menu, but it mixed up with the page content.

**Comment by ayshsandu** [comment]
Fixed in the latest https://is.docs.wso2.com/en/5.9.0/learn/openid-connect-single-logout/
