### ISSUE TITLE
SP and IdP configuration topics are confusing

### ISSUE THREAD

**Issue by malithie** [wso2/docs-is#160]
**Description:**
As I searched on configuring a 'SAML IdP', I came across a content which shows 'File based SP configurations'.
I was just referring the side topics there which is so confusing on what actually it denotes.

![image](https://user-images.githubusercontent.com/4951983/64072814-ca318a00-ccb2-11e9-9a16-18f23833732d.png)

It doesn't make send to add a service provider in identity provider IS.
In WSO2 Identity Server, we would be able to configure 'service providers' and 'identity providers'
So it should be,
- configuring a Service Provider
- configuring an Identity Provider

Each might then break based on the protocol and on the fact if configuration is file based on UI based.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/908
