### ISSUE TITLE
Onboard users with Ask Password Documentation priority of steps is misleading

### ISSUE THREAD

**Issue by denuwanthi** [wso2/docs-is#161]
**Description:**
1. In https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/creating-users-using-the-ask-password-option/ 

under "Follow the steps given below to configure WSO2 IS to enable the ask password feature:" section  the 1 st point is to add a configuration to <IS_HOME>/repository/conf/deployment.toml (Make sure the following configuration is added to the <IS_HOME>/repository/conf/deployment.toml file to set the redirection URL valid time period in minutes.
The redirection link that is provided to the user to set the password is invalid after the time specified here has elapsed.)

After that point it says "You can also configure the expiry time through the Management Console." 

But what should be documented is point 1 should be "configure the expiry time through the Management Console"

And then mention after that the configuration <IS_HOME>/repository/conf/deployment.toml is used as deafult, and it can be overriden by the configuration you do on management console.

2.In the same doc the point 2 is not mandatory for creating users in management console

3.The point 3 mention on Configure the email settings in the <IS_HOME>/repository/conf/output-event-adapters.xml file. But it should be changed to use >/repository/conf/deployment.toml and that configuration should be given
ex:
[output_adapter.email]
from_address = "abcd@gmail.com"
username = "abcd"
password = "xxxx"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
