### ISSUE TITLE
OIDC logout document page rendering issues while scrolling

### ISSUE THREAD

**Issue by malithie** [wso2/docs-is#165]
Location : https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Single-Logout/

**Description:**
As scrolling over OIDC logout page noted that sometimes,
- sides bars appears and disappears
- images becomes large

There seems to be rendering problems.
Please refer below images for few such cases

![image](https://user-images.githubusercontent.com/4951983/64073875-bc373580-ccc1-11e9-843a-0841b60337e9.png)

![image](https://user-images.githubusercontent.com/4951983/64073889-c2c5ad00-ccc1-11e9-8c22-844432c8df6c.png)

**Comment by sherenewso2** [comment]
This has been fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/194
