### ISSUE TITLE
OIDC single logout page includes broken links

### ISSUE THREAD

**Issue by malithie** [wso2/docs-is#166]
Location : https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Single-Logout/

**Description:**
In OIDC single logout page, there we three links referring to,
- OIDC Session Management
- OIDC Back-Channel Logout
- OIDC Front-Channel Logout

![image](https://user-images.githubusercontent.com/4951983/64073924-310a6f80-ccc2-11e9-8d1b-19296890b73e.png)

But, clicking on them does not loaded the respective content.

**Comment by sherenewso2** [comment]
This has been fixed with PR [1] 
[1] https://github.com/wso2/docs-is/pull/194
