### ISSUE TITLE
Secondary User Store API documentation is broken

### ISSUE THREAD

**Issue by ayshsandu** [wso2/docs-is#1661]
doc url: https://is.docs.wso2.com/en/latest/develop/userstore-rest-api/

![image](https://user-images.githubusercontent.com/5061791/80621871-91c29580-8a65-11ea-9318-86a6adea5673.png)

**Comment by sherenewso2** [comment]
Fixed with [1] 

[1] https://github.com/wso2/docs-is/pull/1662
