### ISSUE TITLE
Need to change xml configuration to new config model. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/docs-is#169]
Need to change xml configuration in [1] to new config model. 

 ```
   <Resource context="(.*)/oauth2/introspect(.*)" secured="true" http-method="all">
        <Permissions>/permission/admin/manage/identity/applicationmgt/view</Permissions>
    </Resource>
```
[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/invoke-the-oauth-introspection-endpoint/

**Comment by ayshsandu** [comment]
Updated in https://is.docs.wso2.com/en/5.9.0/learn/invoke-the-oauth-introspection-endpoint/
