### ISSUE TITLE
Askpassword with SCIM2 command is incorrect

### ISSUE THREAD

**Issue by denuwanthi** [wso2/docs-is#170]
**Description:**
In [1], the CURL command given for creating users using SCIM2 is wrong correct command is 

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com"}],"**urn:ietf:params:scim:schemas:extension:enterprise:2.0:User**":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Further it is good to provide a sample CURL command for a tenant as well.

Ex:
curl -v -k --user admin@wso2.com:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com"}],"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/t/wso2.com/scim2/Users

[1]https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/creating-users-using-the-ask-password-option/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
