### ISSUE TITLE
Mising deployment.toml configs related to Account Lock Feature

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#180]
**Suggested Labels**
Affected/ IS 5.9.0

In Account Locking email sending we need to include the deployment.toml configs inplace of xml configs

[output_adapter.email]
from_address= "wso2iamtest@gmail.com"
username="wso2iamtest"
password="Wso2@iam70"

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/locking-a-specific-user-account/

**Comment by sherenewso2** [comment]
Fixed with PR [1] 
[1] https://github.com/wso2/docs-is/pull/199
