### ISSUE TITLE
Missing deploymnet.toml configs for enabling admin services

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#181]
**Suggested Labels**
Affected/IS5.9.0

When enabling admin services we need to do the following toml config. Include that config inplace of xml config

[admin_service.wsdl]
enable = true
[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/calling-Admin-Services/

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/develop/calling-admin-services/
