### ISSUE TITLE
Invalid TOML format in "Private Key JWT Client Authentication for OIDC" 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#182]
Suggested Labels
Affected/IS5.9.0

The document[1] following incorrect toml format,
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc/

![image](https://user-images.githubusercontent.com/39120228/64236818-d028a480-cf18-11e9-889c-45fb894fa985.png)

**Comment by ayshsandu** [comment]
Will be addressed in #429
