### ISSUE TITLE
[Doc] Write Adaptive Auth JS API Reference for newly introduced conditional function

### ISSUE THREAD

**Issue by Akila94** [wso2/docs-is#1821]
**Description:**
The [documentation](https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference) (Adaptive Authentication JS API Reference) should be written to the newly introduced inbuilt conditional function in the following PR:

https://github.com/wso2/carbon-identity-framework/pull/2981

The function name is "**fail()**" and takes a map consists of following parameters as an argument,

**errorCode, errorMessage, and errorURI**

All of the above parameters are optional.

**Comment by janakamarasena** [comment]
@Akila94 can you please give the following details of the function

- Function description
- Parameter descriptions
- sample

**Comment by Akila94** [comment]
* Function description: This function redirects the user to the redirect URI provided in the authorization request failing the authorization flow. 
* Parameter description: This function takes a map as an optional parameter. When a map is provided as the parameter, the redirect URL will be appended with following properties which should be contained in the map,

> errorCode (optional): error code to be appended in the redirect URL
> errorMessage (optional): error message to be appended in the redirect URL
> errorURI (opitonal): URI of a web page that includes additional information about the error

Sample code: when a map is used as a parameter

```
var authFailErrorMap = {'errorCode': 'access_denied', 'errorMessage': 'login could not be completed', "errorURI":'http://www.example.com/error'};
fail(authFailErrorMap);
```

**Comment by ruwanta** [comment]
@Akila94 Please create relevant DOC PR

**Comment by Akila94** [comment]
Will update once the Doc PR is created.
