### ISSUE TITLE
Cannot download the sample-auth.war file

### ISSUE THREAD

**Issue by wijith7** [wso2/docs-is#184]
Suggested Labels
Affected/IS5.9.0

Cannot download the sample-auth.war file using the link in doc [1]
[1].
<img width="1643" alt="Screen Shot 2019-09-05 at 11 40 00 AM" src="https://user-images.githubusercontent.com/30929799/64316353-30c7e800-cfd2-11e9-9528-9cfcaed6e5ef.png">

**Comment by gomathyk** [comment]
This is fixed now.
