### ISSUE TITLE
Invalid TOML format in "Configuring a JDBC User Store"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#185]
Suggested Labels
Affected/IS5.9.0
Severity : Critical
Priority : High

The document[1] following incorrect toml format under "sample property JDBC with datasource',
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-a-jdbc-user-store/

![image](https://user-images.githubusercontent.com/39120228/64317021-1989fa00-cfd4-11e9-8173-3d18c99839ab.png)

it should be,========

[user_store]
type = "database"
[user_store.properties]
 read_only  =  false
 read_groups  =  true
 write_groups  =  true
case_insensitive_username  =  true
username_java_regex  =  "^[\\\S]{3,30}$"
username_javascript_regex  =  "^[\\\S]{3,30}$"
username_java_regex_violation_error_msg  =  "Username pattern policy violated"
password_java_regex  =  "^[\\\S]{5,30}$"
password_javascript_regex  =  "^[\\\S]{5,30}$"
password_java_regex_violation_error_msg  =  "Password length should be within 5 to 30 characters"
scim_enabled=false
rolename_java_regex  =  "^[\\\S]{3,30}$"
rolename_javascript_regex  =  "^[\\\S]{3,30}$"
is_bulk_import_supported  =  true
password_digest  =  "SHA-256"
store_salted_password  =  true
multi_attribute_separator  = ","
max_user_name_list_length  =  "100"
max_role_name_list_length  =  "100"
user_roles_cache_enabled  =  true
user_name_unique_across_tenants  =  false

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/199
