### ISSUE TITLE
The page will redirect to empty page,- "Identity Server Documentation WIP Configuring a JDBC User Store"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#186]
Suggested Labels
Affected/IS5.9.0
Document : https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-a-jdbc-user-store/

When click on links, " Setting Up the Physical Database " and "Managing Datasources" the page will redirect to empty page, (Page not found)

![image](https://user-images.githubusercontent.com/39120228/64333672-ae9ceb00-cff4-11e9-9457-75ff8724dcd3.png)

**Comment by sherenewso2** [comment]
Fixed [1] 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-a-jdbc-user-store/
