### ISSUE TITLE
[Urgent] Have a page listing the extension points

### ISSUE THREAD

**Issue by Abilashini** [wso2/docs-is#1874]
have a page listing all the extension points under 'Extending the Identity Server' for the purpose of sharing a single link to showcase all the extension points we have
https://is.docs.wso2.com/en/5.10.0/develop/developer-guide/

Similar to https://docs.wso2.com/display/IS570/Extending+the+Identity+Server

**Comment by gomathyk** [comment]
Should be resolved with https://github.com/wso2/docs-is/pull/1885
