### ISSUE TITLE
Force passed Reset missing deployment.toml configs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#189]
**Suggested Labels**
Affected/IS5.9.0

Under email sending configuration related to force password reset scenarios we need to mention the related deployment.toml configs for email sending configs as below.

[output_adapter.email]
from_address= "wso2iamtest@gmail.com"
username="wso2iamtest"
password="Wso2@iam70"

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/forced-password-reset/

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/199
