### ISSUE TITLE
Broken links related to Force Password Reset

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#190]
**Suggested Labels**
Affected/ IS5.9.0

Links which are mentioned as dashboard ,  UserProfileMgtService admin service  ,  Configuring Password Policy Authenticator  are not working in [1]

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/forced-password-reset/

**Comment by deshankoswatte** [comment]
Hi @ShanikaWickramasinghe,

The links dashboard and UserProfileMgtService admin service are only accessible when an Identity Server is up and running. The link Configuring Password Policy Authenticator is fixed. The assumptions were based on [1].

[1] - https://is.docs.wso2.com/en/5.9.0/learn/forced-password-reset/

**Comment by ShanikaWickramasinghe** [comment]
Hi @deshankoswatte,
We can close the issue based on the above comment
