### ISSUE TITLE
Internal links not working properly - "OpenID Connect Hybrid Flow"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#191]
Suggested Labels
Affected/IS5.9.0
Document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Hybrid-Flow/#OpenIDConnectHybridFlow

![image](https://user-images.githubusercontent.com/39120228/64336070-c034c180-cff9-11e9-8fc2-d765a3a65580.png)

2. 
![image](https://user-images.githubusercontent.com/39120228/64336125-e22e4400-cff9-11e9-89cb-333c9445b445.png)

3. 
![image](https://user-images.githubusercontent.com/39120228/64336195-0558f380-cffa-11e9-9ee7-809724915e06.png)

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/194
