### ISSUE TITLE
Include a sample SOAP request for Force password reset scenario when the user is in a secondary userstore

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#192]
**Suggested Labels**
Affected / IS 5.9.0

Include a sample soap request for a scenario where the user is configured in a secondary user store. In such a scenario related soap request needs to be as below where username needs to be mentioned as 

 <mgt:username>SECONDARY-ALPHA2/shanika</mgt:username>
Note : here SECONDARY-ALPHA2 is the domain name used for the secondary userstore

Sample Request
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mgt="http://mgt.profile.user.identity.carbon.wso2.org" xmlns:xsd="http://mgt.profile.user.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <mgt:setUserProfile>
         
         <mgt:username>SECONDARY-ALPHA2/shanika</mgt:username>
         
         <mgt:profile>
            
            <xsd:fieldValues>
               
               <xsd:claimUri>http://wso2.org/claims/identity/adminForcedPasswordReset</xsd:claimUri>
               <xsd:fieldValue>true</xsd:fieldValue>
            </xsd:fieldValues>
            <xsd:profileName>default</xsd:profileName>
         </mgt:profile>
      </mgt:setUserProfile>
   </soapenv:Body>
</soapenv:Envelope>`

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/forced-password-reset/

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/912
