### ISSUE TITLE
Internal links not working properly - "Installing as a Windows Service"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#195]
Suggested Labels
Affected/IS5.9.0
Severity : Medium
Priority : Medium

Document: https://is.docs.wso2.com/en/5.9.0/admin-guide/installing-as-a-Windows-Service/

![image](https://user-images.githubusercontent.com/39120228/64411329-8f609500-d0aa-11e9-8a84-92c5d61950a5.png)

**Comment by ayshsandu** [comment]
FIxed in the latest https://is.docs.wso2.com/en/5.9.0/setup/installing-as-a-windows-service
