### ISSUE TITLE
Link does not redirect to the "Carbon Secure Vault Implementation" page 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#196]
Suggested Labels
Affected/IS5.9.0
Document: https://is.docs.wso2.com/en/5.9.0/admin-guide/installing-as-a-Windows-Service/

![image](https://user-images.githubusercontent.com/39120228/64411924-eadf5280-d0ab-11e9-9b42-090e5995a2cc.png)

**Comment by ayshsandu** [comment]
Fixed in the latest https://is.docs.wso2.com/en/5.9.0/setup/installing-as-a-windows-service/
