### ISSUE TITLE
Invalid syntax in Adaptive Script API reference documentation 

### ISSUE THREAD

**Issue by mevan-karu** [wso2/docs-is#1969]
**Description:**
When retrieving parameters in the authentication request via an adaptive script, our current documentation [1] states as `request.params[“<param_name>”]`, but this syntax is not working. 

The following syntax `request.params.param_name[0]` is returning the value assigned to the given parameter.  

[1] https://is.docs.wso2.com/en/latest/references/adaptive-authentication-js-api-reference/#request-object

**Comment by sherenewso2** [comment]
Resolved with #2135 and #2136
