### ISSUE TITLE
Should update with latest wso2 Identity Server product name

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#198]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/admin-guide/installing-as-a-Windows-Service/

![image](https://user-images.githubusercontent.com/39120228/64414648-5972df00-d0b1-11e9-8e69-8636a73081c4.png)

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/880/
