### ISSUE TITLE
Broken Link to cURL commands.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/docs-is#2002]
**Description:**
The bottom link at https://is.docs.wso2.com/en/latest/learn/configuring-user-stores-for-scim-2.0-based-inbound-provisioning/ to 'https://is.docs.wso2.com/en/latest/develop/using-the-scim-2.0-rest-apis' is broken.

'You can see the sample cURL commands for all SCIM 2.0 operations **here**.'

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2131
