### ISSUE TITLE
Issues with Changing to Databases,

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#201]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruwanta** [comment]
There are lot of unfinished XML documents, which should have been replaced with TOML config

https://is.docs.wso2.com/en/5.9.0/administer/changing-to-mariadb/
https://is.docs.wso2.com/en/5.9.0/administer/changing-to-mysql/


e.g.
"Updating other configuration files"

"defaultAutoCommit"

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/setup/working-with-databases/
