### ISSUE TITLE
Missing information in SCIM 2.0 swagger

### ISSUE THREAD

**Issue by mefarazath** [wso2/docs-is#2048]
**Description:**

The SCIM 2.0 API docs (https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis) are missing information about the required scopes for each operation when authenticating with an access token.

For example, the GET /Users require authenticating with an access token having scope 'internal_user_mgt_list'. This information can be found by looking at the identity.xml which configures how each endpoint is secured. 

```
       <Resource context="(.*)/scim2/Users" secured="true" http-method="GET">
            <Permissions>/permission/admin/manage/identity/usermgt/list</Permissions>
            <Scopes>internal_user_mgt_list</Scopes>
        </Resource>
```

But ideally, this information needs to be part of the swagger definition just like how we have included the required permissions to do each operation.

**Affected Product Version:**
5.10.0, 5.9.0

**Related Issues:**
https://github.com/wso2/product-is/issues/9431

**Comment by pavinduLakshan** [comment]
This is completed now for docs for all the mentioned product versions. Hence closing
