### ISSUE TITLE
Broken link (Page navigate to empty page)  Introduction Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#205]
Suggested Labels
Affected/IS5.9.0

Document: https://is.docs.wso2.com/en/5.9.0/getting-started/overview/

![image](https://user-images.githubusercontent.com/39120228/64505515-bb218c00-d2f1-11e9-8735-a8bb510a261b.png)

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228
