### ISSUE TITLE
Directing to Page Not Found pages from Architecture Page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#206]
**Suggested Labels**
Affected/IS5.9.0 

Directing to Page Not Found pages from Architecture Page. For example click on the hyperlink  IWA (Integrated Windows Authentication) and it will direct to page not found

[1]. https://is.docs.wso2.com/en/5.9.0/getting-started/architecture/

**Comment by ayshsandu** [comment]
Fixed in https://is.docs.wso2.com/en/5.9.0/get-started/architecture/
