### ISSUE TITLE
Incorrect session data key config

### ISSUE THREAD

**Issue by GANGANI** [wso2/docs-is#2072]
**Description.**

Under the OS-Level security guidelines, session data key config [1] needs to be changed.

**Improvement**

The config in the doc [1] needs to be updated as follows.

```
[session_data.cleanup]
clean_expired_session_data_in_chunks_of = "8192"
```

**Related Issues:**

If someone tries this config mentioned in this doc, the "Local Authenticators do not list after adding the session data cleanup config" issue [2] will occur.

[1] https://is.docs.wso2.com/en/latest/administer/os-level-security-guidelines/#session-data
[2] https://github.com/wso2/product-is/issues/9437

**Comment by gomathyk** [comment]
Will be resolved with the above-mentioned PRs.
