### ISSUE TITLE
Directing to Page Not Found page from Quick Start Guide page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#208]
**Suggested Labels**
Affected/IS 5.9.0
Directing to Page Not Found page from Quick Start Guide Page. Click on **Start** hyperlink it will direct to a Page Not found page

[1]. https://is.docs.wso2.com/en/5.9.0/getting-started/quick-start-guide/

**Comment by ayshsandu** [comment]
Fixed in https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/
