### ISSUE TITLE
Configs for validating iat of JWT tokens

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#2085]
**Description:**
Related to https://github.com/wso2/product-is/issues/9425

In the doc[1] following config exists and its outdated.
```
<JWTGrant>            
    <EnableIATValidation>true</EnableIATValidation>            
    <IATValidityPeriod>30</IATValidityPeriod>
</JWTGrant>
```
The following configurations needs to be added to the doc instead of the above.

```
[oauth.grant_type.jwt]
enable_iat_validation="true"
iat_validity_period=30
```

Toml config PR: https://github.com/wso2/carbon-identity-framework/pull/3106

[1] - https://is.docs.wso2.com/en/latest/learn/jwt-grant/

**Comment by sherenewso2** [comment]
resolved with #2134
