### ISSUE TITLE
Page Not found for Creating users and roles, Configuring web app for SSO and Consent Management .

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#209]
**Suggested Labels**
Affected/IS 5.9.0

In Quick start guide the hyperlink given for 

 Creating users and roles
 Consent Management .
 Configuring web app for SSO.

Will display as Page Not Found

[1]. https://is.docs.wso2.com/en/5.9.0/getting-started/quick-start-guide/#QuickStartGuide-WFStep01

**Comment by sherenewso2** [comment]
Fixed with PR [1]
[1] https://github.com/wso2/docs-is/pull/202
