### ISSUE TITLE
[DOC] Disable extending the rememberMe expiry time on every auth request

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#2096]
**Description:**
During each authentications request, the expiry time of commonAuth cookie will be extended OOTB. However, with the following config, this feature can be switched off. These details needs to be added to doc[1].

Introduced from PR: https://github.com/wso2/carbon-identity-framework/pull/3131

```
[session.timeout]
extend_remember_me_session_timeout_on_auth=false
```

[1] - https://is.docs.wso2.com/en/latest/learn/configuring-session-timeout/

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2130.
