### ISSUE TITLE
Redirecting to wrong version

### ISSUE THREAD

**Issue by nilasini** [wso2/docs-is#2103]
**Description:**
The link REST API swagger docs on account recovery in \[1] are redirecting to 5.1.0 docs\[2] instead of the latest one. Check all the versions. Seems all version of doc[1] is like that.

Need to refactor the doc \[2] because there are API duplications.

\[1] https://is.docs.wso2.com/en/latest/develop/using-the-account-recovery-rest-apis/
\[2] https://docs.wso2.com/display/IS510/apidocs/account-recovery/

**Comment by gomathyk** [comment]
The ones with 510 in the URL are for the 5.10.0 version. We do not have rest API docs for 5.1.0.
