### ISSUE TITLE
Email Signature configuration is not documented

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/docs-is#2107]
**Description:**
In [1] there are configurations for configuring the email module but here the **signature** configuration is not documented. But this was documented in [2] in xml format. For the toml format this configuration can be added as below.

> [output_adapter.email]
signature = "ABC.com"

[1] https://is.docs.wso2.com/en/5.10.0/setup/configuring-email-sending/#configuring-the-email-sending-module
[2] https://is.docs.wso2.com/en/latest/learn/tenant-wise-email-sender-configuration/

**Suggested Labels:**
IS-5.9.0, IS-5.10.0

**Comment by gomathyk** [comment]
Will be resolved with https://github.com/wso2/docs-is/pull/2126.
