### ISSUE TITLE
Sidebar (Side Navigation-Left) menu is not displaying in "Identity Provider Configurations used with APIs"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#213]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-Provider-Configurations-used-with-APIs/#google-configuration

**Comment by sherenewso2** [comment]
This page is fixed now [1] 
[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-provider-configurations-used-with-apis/#google-configuration
