### ISSUE TITLE
Broken Links- Identity Provider Configurations used with APIs

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#215]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-Provider-Configurations-used-with-APIs/

![image](https://user-images.githubusercontent.com/39120228/64527136-c50fb300-d322-11e9-917f-e33f19270829.png)

![image](https://user-images.githubusercontent.com/39120228/64527190-ea042600-d322-11e9-967e-e99e1f687d5f.png)

**Comment by sherenewso2** [comment]
This page is fixed now [1] 
[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-provider-configurations-used-with-apis/
