### ISSUE TITLE
Outdated doc- Configuring OAuth2-OpenID Connect document

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#220]
Suggested Labels
Affected/IS5.9.0

document: Configuring OAuth2-OpenID Connect
https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-oauth2-openid-connect/

Document should be updated according to the current implementation.
And there is no any details about "Userinfo Endpoint URL" and the attached image also outdated. (sub section -step 4)

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/880
