### ISSUE TITLE
Page navigate to empty page- Configuring OAuth2-OpenID Connect

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#221]
Suggested Labels
Affected/IS5.9.0

document: Configuring OAuth2-OpenID Connect
https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-oauth2-openid-connect/
![image](https://user-images.githubusercontent.com/39120228/64530216-36069900-d32a-11e9-9734-aefa609e2946.png)

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228
