### ISSUE TITLE
Page navigate to empty page- Configuring OAuth2-OpenID Connect Single-Sign-On

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#222]
Suggested Labels
Affected/IS5.9.0

document: Configuring OAuth2-OpenID Connect Single-Sign-On
https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-oauth2-openid-connect-single-sign-on/

![image](https://user-images.githubusercontent.com/39120228/64532134-8e3f9a00-d32e-11e9-8e6e-04d3173e8da4.png)

![image](https://user-images.githubusercontent.com/39120228/64532626-77e60e00-d32f-11e9-988a-46535690f482.png)

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228
