### ISSUE TITLE
Page navigate to empty page-Delegated Access Control

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#223]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/delegated-access-control/
![image](https://user-images.githubusercontent.com/39120228/64532458-2b023780-d32f-11e9-866f-16da997d011f.png)

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/228
