### ISSUE TITLE
Missing document for Terminating User Sessions for IS 5.7.0 and IS 5.8.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#224]
Affected/ IS 5.7.0 and IS 5.8.0

Missing document for Terminating User Sessions for doc space IS 5.7.0 and IS 5.8.0

[1]. https://docs.wso2.com/display/IS560/Terminating+User+Sessions

**Comment by ayshsandu** [comment]
In IS-5.7.0 and IS-5.8.0, above Session Termination capability is not available OOTB.
Reason being, IS analytics 5.6.0 and below are based on DAS. IS 5.7.0 and later versions are based on Stream Processor. Above [session termination works]( https://docs.wso2.com/display/IS560/Terminating+User+Sessions) only with DAS.

IS-5.9.0 onwards, this session termination capability is available OOTB in the product without needing to set up any Analytics profile.
