### ISSUE TITLE
Pointing to a older EI version doc from workflow management page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#232]
Affected/ IS 5.9.0

Hyperlink given for **Business Process Management (BPM) component of WSO2 Enterprise Integrator** from the page workflow management is directing a older version of EI. We need to point to a latest EI version that is compatible with IS 5.9.0 [1]

This needs to be fixed in [2] as well for the hyperlink **Business Process Management (BPM) component of WSO2 Enterprise Integrator**

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/workflow-management/
[2]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/adding-a-workflow-engine/

**Comment by gomathyk** [comment]
Will be resolved with https://github.com/wso2/docs-is/pull/918/files.
