### ISSUE TITLE
BPS worker and manger host default values need to be changes

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#233]
Affected/IS 5.9.0

Default values mentioned for **BPS Manager Host Services URL** and **BPS Worker Host Services URL** needs to be changed as below as we havent instructed users to strat the pack with a offset.

BPS Manager Host Services URL | The host URL of the BPS manager node. | https://localhost:9444/services (This points to the manager node of WSO2 BPS that is already running.)

BPS worker host https://localhost:9443/services 
BPS manager host host https://localhost:9443/services 

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/adding-a-workflow-engine/

**Comment by sherenewso2** [comment]
Fixed with PR [1] 

[1] https://github.com/wso2/docs-is/pull/244
