### ISSUE TITLE
Directing to a page not found from adding a new work flow definition page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#234]
Affected/IS 5.9.0

Hyper link given for **here**  from the page adding a new work flow definition is directing to a Page not found

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/adding-a-new-workflow-definition/

**Comment by ayshsandu** [comment]
No broken links in the latest https://is.docs.wso2.com/en/5.9.0/learn/adding-a-new-workflow-definition/
