### ISSUE TITLE
Internal links are not working properly

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#239]
Suggested Labels
Affected/IS5.9.0

document: OpenID Connect Logout URL Redirection
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openid-connect-logout-url-redirection/

![image](https://user-images.githubusercontent.com/39120228/64692635-40a06a00-d4b3-11e9-80a5-272e949168ff.png)

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/openid-connect-logout-url-redirection/
