### ISSUE TITLE
UI Issue- OpenID Connect Logout URL Redirection

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#240]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Logout-URL-Redirection/

![image](https://user-images.githubusercontent.com/39120228/64693062-14391d80-d4b4-11e9-9278-328f6f53b04a.png)

**Comment by sherenewso2** [comment]
Fixed [1] 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openid-connect-logout-url-redirection/
