### ISSUE TITLE
Internal links are not working as expected

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#241]
Suggested Labels
Affected/IS5.9.0

document: JSON Web Key Set Endpoint
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/jSON-Web-Key-Set-Endpoint

![image](https://user-images.githubusercontent.com/39120228/64693326-a2ad9f00-d4b4-11e9-8f62-dbe7d34d1e26.png)

**Comment by sherenewso2** [comment]
This page has been fixed now [1] 

https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/json-web-key-set-endpoint/
