### ISSUE TITLE
Navigate to Empty page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#242]
Suggested Labels
Affected/IS5.9.0

When click on the mentioned links, 
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect/

![image](https://user-images.githubusercontent.com/39120228/64697033-8b26e400-d4bd-11e9-9fa3-745d47d8219f.png)

**Comment by sherenewso2** [comment]
This page has been fixed now [1] 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openid-connect/
