### ISSUE TITLE
Internal links are not working as expected 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#243]
Suggested Labels
Affected/IS5.9.0

Document: OpenID Connect Hybrid Flow
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openID-Connect-Hybrid-Flow

![image](https://user-images.githubusercontent.com/39120228/64704774-700fa080-d4cc-11e9-982f-895a9029adaf.png)

**Comment by sherenewso2** [comment]
Fixed [1] 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/openid-connect-hybrid-flow
