### ISSUE TITLE
Links navigate to empty page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#247]
Suggested Labels
Affected/IS5.9.0

document: Analytics
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/analytics/

![image](https://user-images.githubusercontent.com/39120228/64938355-37304c80-d87b-11e9-9b8b-38aab1c4872a.png)

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/analytics/
