### ISSUE TITLE
Links are not working as expected

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#248]
Suggested Labels
Affected/IS5.9.0

document: Prerequisites to Publish Statistics
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/prerequisites-to-Publish-Statistics/

![image](https://user-images.githubusercontent.com/39120228/64939742-a5770e00-d87f-11e9-8453-0d0d010044dc.png)

![image](https://user-images.githubusercontent.com/39120228/64939777-bfb0ec00-d87f-11e9-960e-b132e4a03689.png)

![image](https://user-images.githubusercontent.com/39120228/64943055-51245c00-d888-11e9-8867-bdf2d78e0fbc.png)

![image](https://user-images.githubusercontent.com/39120228/64943086-6d27fd80-d888-11e9-9c09-312be89a0945.png)

![image](https://user-images.githubusercontent.com/39120228/64943120-8761db80-d888-11e9-8266-0bbce98212ae.png)

**Comment by GDRDABARERA** [comment]
These linking issues are fixed in latest 5.9.0 docs. Hence closing
