### ISSUE TITLE
Links navigate to old version of SP(Stream Processor ) documents.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#249]
Suggested Labels
Affected/IS5.9.0

document: Prerequisites to Publish Statistics
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/prerequisites-to-Publish-Statistics/

![image](https://user-images.githubusercontent.com/39120228/64942850-cb081580-d887-11e9-870f-9cc7cc958f49.png)

![image](https://user-images.githubusercontent.com/39120228/64942905-ec690180-d887-11e9-903e-c9df32cb8fdd.png)

![image](https://user-images.githubusercontent.com/39120228/64942979-1e7a6380-d888-11e9-9680-a3d3f690dbac.png)

![image](https://user-images.githubusercontent.com/39120228/64943225-cd1ea400-d888-11e9-8cb6-4c7dece6a077.png)

**Comment by GDRDABARERA** [comment]
These issues are fixed in latest 5.9.0. hence closing this issue.
