### ISSUE TITLE
Make introspection endpoint permssion configurable from deployment.toml

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#262]
In https://is.docs.wso2.com/en/5.9.0/learn/invoke-the-oauth-introspection-endpoint/

We have a provided a XML config to update the permissions to invoke introspection endpoint using identity.xml file. This is currently not configurable from deployment.toml. 

```
<Resource context="(.*)/oauth2/introspect(.*)" secured="true" http-method="all">
        <Permissions>/permission/admin/manage/identity/applicationmgt/view</Permissions>
    </Resource>
```

We need to make it configurable similar to SCIM2 me enpoint. or better to remove the above config from doc

```
        {% if resource_access_control.scim2_me_get_method.keep_resource is sameas true %}
        <Resource
                context="(.*)/scim2/Me"
                secured="{{resource_access_control.scim2_me_get_method.secured}}"
                http-method="GET">
            <Permissions>{{resource_access_control.scim2_me_get_method.permission}}</Permissions>
        </Resource>
        {% endif %}``

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/invoke-the-oauth-introspection-endpoint/
