### ISSUE TITLE
Issues in "Configuring Single Sign-On" document.. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/docs-is#263]
Following issues are there in doc [1]

- downloading-a-sample.md is missing. 
Thus broken link found - https://is.docs.wso2.com/en/5.9.0/learn/downloading-a-sample
- Column lengths are not user-friendly in "Click here for more information on each attribute" hidden table. 
- Note is not rendered in "Enable IdP Initiated SSO" section
- "Configuring SAML 2.0 Artifact Binding" link is broken. 
- "Querying SAML Assertions" link is broken.
- "Related Topics" - bullet points should be aligned. "OAuth2-OpenID Connect" and "Integrated Windows Authentication" links are broken

[1] https://is.docs.wso2.com/en/5.9.0/learn/configuring-single-sign-on/

**Comment by ayshsandu** [comment]
Most of the issues are already fixed, some are fixed in https://github.com/wso2/docs-is/pull/880
