### ISSUE TITLE
Missing link for oauth-token-validation-using-soap-service

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#268]
In https://is.docs.wso2.com/en/5.9.0/learn/oauth-token-validation-using-soap-service/, 'WSO2 playground2' link is broken, and in docs-is , markdown is missing for that URL.

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/oauth-token-validation-using-soap-service/
