### ISSUE TITLE
Content should be updated when EI configurations are  modified with new configurations (TOML format)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#271]
Document : **Configuring the BPM Profile of WSO2 EI as a Workflow Engine**
https://is.docs.wso2.com/en/5.9.0/learn/configuring-the-bpm-profile-of-wso2-ei-as-a-workflow-engine/

In above mentioned page, configurations are maintained by XML based, but  when EI configurations are  modified with new configurations model (TOML format) those content should be change.

**Comment by gomathyk** [comment]
The following document has been modified now:
https://is.docs.wso2.com/en/5.9.0/learn/configuring-the-bpm-profile-of-wso2-ei-as-a-workflow-engine/
