### ISSUE TITLE
Content should be updated when 5.9.0 GA pack is released 

### ISSUE THREAD

**Issue by Isanka95** [wso2/docs-is#274]
**Description:**

In **Configuring a Service Provider for Adaptive Authentication** page (https://is.docs.wso2.com/en/5.9.0/learn/configuring-a-service-provider-for-adaptive-authentication/
), 
_**org.wso2.carbon.identity.sample.extension.authenticators-5.7.0.jar**_ should be updated to 5.9.0 version when 5.9.0 GA pack is released.

![git_issue](https://user-images.githubusercontent.com/36721128/65019522-0585b700-d949-11e9-8aa1-2a57144a42f2.png)

**Comment by ayshsandu** [comment]
Fixed in the latest document space.
PR: https://github.com/wso2/docs-is/pull/913
