### ISSUE TITLE
Page Not Found in "Configuring WSO2 EI Entitlement Mediator with Identity Server"

### ISSUE THREAD

**Issue by IsharaSandeepanie** [wso2/docs-is#283]
**Description:**
Both the links    [Adding a Proxy Service in the WSO2 EI documentation](url) in 5.9.0 and [Adding a Proxy Service ](url)in 5.8.0 are referred to page not found.

following links are also referred to page not found in both 5.8.0 and 5.9.0
[Adding a Mediator to a Sequence](url)
[Mediators](url)

**Comment by ayshsandu** [comment]
This document is removed from the latest documentation site.
