### ISSUE TITLE
Navigation pane scroll bar is disable in chrome browser

### ISSUE THREAD

**Issue by aaujayasena** [wso2/docs-is#291]
Label :
Version: 5.9
Severity: Critical
priority: High

Navigation pane scroll bar is available in other browser but in chrome it's not available. 

In the Firefox browser
![image](https://user-images.githubusercontent.com/39077751/65028095-1b9b7380-d959-11e9-8685-ac3e71d7ea3f.png)

In the Chrome browser (Scroll bar is not available. )
![image](https://user-images.githubusercontent.com/39077751/65028168-3ec62300-d959-11e9-993e-cc1e3b658a96.png)

**Comment by gomathyk** [comment]
This is fixed now.
