### ISSUE TITLE
handling custom claims with openid connect doc contains deprecated content

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#310]
In the doc https://is.docs.wso2.com/en/5.9.0/learn/handling-custom-claims-with-the-jwt-bearer-grant-type/  it talks about mapping the custom claim for openid scope by updating the registry resource. From IS 5.7.0 we have introduced OIDC scopes and we don't have oidc file the registry. We need to update the doc with the newest content [1]

[1] - http://hasanthipurnima.blogspot.com/2018/07/oidc-scope-claim-mapping-in-is-570.html

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/890
