### ISSUE TITLE
CacheManager in identity.xml needs to be templated to supported additional cache configurations for connectors

### ISSUE THREAD

**Issue by emswbandara** [wso2/docs-is#324]
In https://is.docs.wso2.com/en/5.9.0/learn/private-key-jwt-client-authentication-for-oidc/, it contains an XML config to configure PrivateKeyJWT cache in identity.xml.
```

<CacheConfig>
    <CacheManager name="IdentityApplicationManagementCacheManager">
    <Cache name="PrivateKeyJWT" enable="true" timeout="10" capacity="5000" isDistributed="false"/>
    </CacheManager>
</CacheConfig>

```
 Currently the `<CacheManager> `element is not templated to add new caches. We need to allow to support additional cache configurations in this.

**Comment by ayshsandu** [comment]
Fixed in https://is.docs.wso2.com/en/5.9.0/learn/private-key-jwt-client-authentication-for-oidc/
