### ISSUE TITLE
Need to add the Configuring Apple doc to IS 590 doc space

### ISSUE THREAD

**Issue by ashensw** [wso2/docs-is#327]
**Description:**

Need to add a similar doc to this (https://docs.wso2.com/display/IS580/Configuring+Apple) to [IS590 doc space](https://is.docs.wso2.com/en/5.9.0/) as well.  

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by YvonneW** [comment]
The content is available at https://is.docs.wso2.com/en/5.9.0/learn/configuring-apple/
