### ISSUE TITLE
Missing "Working with ACR and AMR" page under Learn/Adaptive Authentication section.

### ISSUE THREAD

**Issue by Isanka95** [wso2/docs-is#333]
**Description:**
Missing "Working with ACR and AMR" page under Learn/Adaptive Authentication section.
Current documentation has this page: https://docs.wso2.com/display/IS580/Working+with+ACR+and+AMR

**Comment by ayshsandu** [comment]
https://is.docs.wso2.com/en/5.9.0/learn/working-with-acr-and-amr/ is added now
