### ISSUE TITLE
Swagger docs not available.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/docs-is#342]
Labels:
Product version: 5.9
Severity: Critical
Priority: High

Git based swagger docs missing for following pages.

1. https://docs.wso2.com/display/IS580/apidocs/Configuration-management-apis/index.html#!/operations#ResourceType#resourceTypePost
2. https://docs.wso2.com/display/IS580/apidocs/Configuration-management-apis
3. https://docs.wso2.com/display/IS580/apidocs/account-recovery/
4. https://docs.wso2.com/display/IS580/apidocs/self-registration/
5. https://docs.wso2.com/display/IS580/apidocs/Authentication-framework-apis/
6. https://docs.wso2.com/display/IS580/apidocs/User-export-apis/
7.https://docs.wso2.com/page-not-found#!/operations#Attribute#resourceResourceTypeResourceNamePost

Above pages come up in following git docs

1. https://docs.wso2.com/display/IS580/Using+the+Account+Recovery+REST+APIs
2. https://docs.wso2.com/display/IS580/Using+the+Authentication+REST+APIs
3. https://docs.wso2.com/display/IS580/Using+the+Consent+Management+REST+APIs?src=sidebar
4. https://docs.wso2.com/display/IS580/Using+the+Personal+Information+Export+REST+APIs
5. https://docs.wso2.com/display/IS580/Using+the+Personal+Information+Export+REST+APIs

**Comment by YvonneW** [comment]
This issue is fixd now.
