### ISSUE TITLE
Broken link for "Prerequisites to Publish Statistics"

### ISSUE THREAD

**Issue by dewniMW** [wso2/docs-is#353]
Broken link for "build the source code" under "Step 01: Download WSO2 IS Analytics" in [1].

Affected in 5.8.0 and 5.7.0 doc space as well. The link in 5.6.0 doc directs to [2]. However this document is outdated for latest product versions.

[1] https://is.docs.wso2.com/en/5.9.0/learn/prerequisites-to-publish-statistics/
[2] https://docs.wso2.com/display/DAS320/Building%20from%20Source

**Comment by ayshsandu** [comment]
Removed building from source option in latest docs
