### ISSUE TITLE
Null value in the screenshot of docs

### ISSUE THREAD

**Issue by IsuraD** [wso2/docs-is#358]
Null value in the screenshot of https://is.docs.wso2.com/en/5.9.0/learn/single-sign-on-for-native-ios-applications-with-wso2-identity-server/ doc

<img width="165" alt="null" src="https://user-images.githubusercontent.com/8455535/65104767-44227c80-d9f0-11e9-9f63-3ff75d1a200d.png">

**Comment by ayshsandu** [comment]
There is a note explaining null.

![explain-null](https://user-images.githubusercontent.com/5061791/69606608-46850080-1049-11ea-9369-d175608cf7a8.png)
