### ISSUE TITLE
Screenshot of configuring-saml-2.0-web-sso docs in outdated. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/docs-is#360]
https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml-2.0-web-sso
![qualifier](https://user-images.githubusercontent.com/8455535/65105322-2eae5200-d9f2-11e9-8e93-59259f442641.png)
/

"Service Provider Qualifier" section is missing.

**Comment by IsuraD** [comment]
Also, description regarding the "Service Provider Qualifier" should be added to the docs.

**Comment by dewniMW** [comment]
The PR [1] has the newly added service provider configurations (Service Provider Qualifier and IdP Entity ID Alias). The screenshot was also updated with this PR. However these changes are not reflected in the latest document. @gomathyk can you check on the reason for this?

[1] https://github.com/wso2/docs-is/pull/89/files

**Comment by gomathyk** [comment]
it's pointing to the wrong file. the corrected file is, https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml2-web-single-sign-on/ but the left navigation points to https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml-2.0-web-sso/. 

will be corrected with https://github.com/wso2/docs-is/pull/369/files
