### ISSUE TITLE
Documentation issues in "configuring-saml-2.0-artifact-binding/"

### ISSUE THREAD

**Issue by IsuraD** [wso2/docs-is#362]
**Description:**
link - https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml-2.0-artifact-binding/

- Should remove the hyperlink in "navigate to Service Providers > Add in the Main menu of the management console and add a new service provider called " saml2-web-app-dispatch.com "" section.
- link to https://is.docs.wso2.com/en/5.9.0/assets/attachments/saml2-web-app-dispatch.com.war is not working

**Comment by ayshsandu** [comment]
Fixed in latest https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml-2.0-artifact-binding/
