### ISSUE TITLE
Formatting issue in "Enabling Geolocation Based Statistics"

### ISSUE THREAD

**Issue by dewniMW** [wso2/docs-is#363]
In doc [1] following issue was found out at the bottom-most tip section.

<img width="710" alt="Screen Shot 2019-09-18 at 9 44 19 AM" src="https://user-images.githubusercontent.com/24982871/65111261-fbbb8c80-d9f8-11e9-8e4b-cb2f153a3f9f.png">

[1] https://is.docs.wso2.com/en/5.9.0/learn/enabling-geolocation-based-statistics/

**Comment by gomathyk** [comment]
This is fixed now.
