### ISSUE TITLE
Add recovery callback url regex config under security guidelines 

### ISSUE THREAD

**Issue by Kanapriya** [wso2/docs-is#3691]
**Description:**
The instruction given in [1] is missing in IS 6.0.0 and IS 6.1.0 docs space. This needs to be added to the relevant docs space.

[1] https://is.docs.wso2.com/en/5.11.0/administer/product-level-security-guidelines/#callback-url-regular-expressions

**Suggested Assignees:**

**Affected Product Version:**
IS 6.0.0
IS 6.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by mpmadhavig** [comment]
**Affected Product Version:**
- IS 5.8.0
- IS 5.9.0
- IS 5.10.0
- IS 6.0.0
- IS 6.1.0
