### ISSUE TITLE
Search bar unresponsive for some time during first load

### ISSUE THREAD

**Issue by omindu** [wso2/docs-is#413]
**Steps to reproduce**

Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit) 

- Access https://is.docs.wso2.com in an incognito window
- Open developer tools
- Click on 'Disable cache' checkbox
![image](https://user-images.githubusercontent.com/9883427/65605705-35772f00-dfc7-11e9-91fe-14db3f9be88f.png)
- Reload the page while the developer tool window is open
- Once the page is loaded, click on the search bar and start typing
- The search bar becomes unresponsive when keeping on typing

**Comment by gomathyk** [comment]
This is resolved now with the new search bar.
