### ISSUE TITLE
 It is better if we can add a brief description(purpose) about the Authorized Apps REST APIs

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#415]
Suggested Labels
Affected/IS5.9.0
REST API- OAuth2 Authorized Apps API v1

“This is the RESTful API for managing OAuth2 Authorized Apps”, with this short description,  it is difficult to understand how and when the user can access mentioned API’s.

So it is better to add a prerequisite and more details to understand the purpose of API and access mentioned REST API’s.

Ref: https://is.docs.wso2.com/en/5.9.0/develop/authorized-apps-rest-api/#/me/listLoggedInUserAuthorizedApps

**Comment by omindu** [comment]
This is the RESTful API for managing OAuth2 Authorized Apps. Through this API, users can view and revoke the OAuth2/OIDC applications which they have permanently provided consent (by clicking on 'Approve Always' during OAuth2 user consent collection) to act on behalf of the user without continuously requesting consent.

Additionally, privileged user can view and revoke other users' authorized apps using the API.
