### ISSUE TITLE
Search for Access Delegation in git docs does not give meaningful results

### ISSUE THREAD

**Issue by mefarazath** [wso2/docs-is#423]
When searching for the term "Access delegation" in https://is.docs.wso2.com/en/5.9.0/ the expected behaviour is to get search results related to OAuth. 

But the results contains docs related to XACML.

**Comment by gomathyk** [comment]
This has the first result related to Oauth 2.0 now followed by XACML docs. Hence closing this. 
<img width="969" alt="access delegation" src="https://user-images.githubusercontent.com/45352240/70128862-a9a71080-16a3-11ea-970e-659a90e6a446.png">
