### ISSUE TITLE
[Docs] GDPR section - should be in the past tense 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#427]
![Screen Shot 2019-08-31 at 10 42 40 AM](https://user-images.githubusercontent.com/54733286/64059530-15c53480-cbdc-11e9-97f7-d65c557263cc.png)

Law is already in effect hence the tense should change. The date should also read May 25, 2018.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/900
