### ISSUE TITLE
[Clustering] Invalid database descriptions 

### ISSUE THREAD

**Issue by isharailanga** [wso2/docs-is#441]
**Description:**
doc link : https://docs.wso2.com/display/IS570/Setting+Up+Separate+Databases+for+Clustering

![screenshot-docs wso2 com-2019 10 01-15_40_32](https://user-images.githubusercontent.com/14251853/65953914-9b016a80-e462-11e9-9f00-526441cef436.png)

The given database descriptions are invalid.
Should be updated as follows:
WSO2_USER_DB: RDBMS that stores internal roles and permissions.
USERSTORE_DB: RDBMS that acts as a user store.

Also, please look into the table above this image.
The USERSTORE_DB database name should be replaced with **WSO2_USER_DB** to fix $subject.

**Suggested Assignees:**
@YvonneW @sherenewso2 @gomathyk 

**Affected Product Version:**
IS570 doc

**Comment by YvonneW** [comment]
The following pages were updated accordingly:
- https://docs.wso2.com/display/IS570/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS580/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS560/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS550/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS541/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS540/Setting+Up+Separate+Databases+for+Clustering
- https://docs.wso2.com/display/IS530/Setting+Up+Separate+Databases+for+Clustering

**Comment by isharailanga** [comment]
Hey @YvonneW, 
The diagrams look good, can you please check and verify on the below:

> Also, please look into the table above this image.
> The USERSTORE_DB database name should be replaced with WSO2_USER_DB to fix $subject.

**Comment by YvonneW** [comment]
Updated.
