### ISSUE TITLE
IS 5.9.0 Halfway through the doc, instructions are based on old xml based configs.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/docs-is#538]
**Description:**
IS 5.9.0, Halfway thourgh this doc, datasource creation instructions are for old xml based file instead of the deployment.toml file.
[Doc](https://is.docs.wso2.com/en/5.9.0/administer/changing-to-postgresql/#!)

**Affected Product Version:**
5.9.0

**Comment by gomathyk** [comment]
The xml configs have been replaced in https://is.docs.wso2.com/en/5.9.0/setup/changing-to-postgresql/#changing-the-default-datasource. Hence closing the issue.
