### ISSUE TITLE
Subtitles of the product documentation

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#548]
**Description:**
Currently we have different sub topics in each page. But in some pages these sub topics are hard to distinguish (Example [1]). Therefore, it will be convenient if we can **BOLD** the subtitles.

[1] - https://is.docs.wso2.com/en/5.9.0/get-started/overview/#identity-management

**Suggested Labels:**
DOC, IS 5.9.0, IS 5.10.0

**Suggested Assignees:**

**Comment by gomathyk** [comment]
For now please precede the second level headings with ## instead of ###. This will give more prominence to it.
