### ISSUE TITLE
Update the token clean documentation with new config model

### ISSUE THREAD

**Issue by sarubi** [wso2/docs-is#555]
**Description:**
Currently "[Removing Unused Tokens from the Database](https://is.docs.wso2.com/en/5.9.0/administer/removing-unused-tokens-from-the-database/)"  documentation described about the old model of enabling the token clean up. 

Need to be updated accordingly with new config model configurations. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by YvonneW** [comment]
The docs will be updated with this https://github.com/wso2/docs-is/pull/557.
