### ISSUE TITLE
Update the Data Purging documentation with latest session data clean up script

### ISSUE THREAD

**Issue by sarubi** [wso2/docs-is#560]
**Description:**
All the "Data Purging" documentation didn't get updated with the latest session data clean up script which we can find [here](https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures) under the step 3. 

We need to update the doc with latest script and also need to point to the following the link to get clean up script for other DBs as well. 
https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures 

[1] https://docs.wso2.com/display/IS570/Data+Purging
[2] https://is.docs.wso2.com/en/5.9.0/administer/data-purging/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by YvonneW** [comment]
The 5.9.0 content will be updated along with https://github.com/wso2/docs-is/pull/566.
