### ISSUE TITLE
Embedded links are not working

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#573]
**Description:**

Doc [1] contains three bullet points linking the subsections of the same page.  When clicked, the user is not navigated to the linked section.

[1] - https://github.com/wso2/docs-is/blob/5.9.0/en/docs/setup/running-the-product.md#running-the-product

**Suggested Labels:**
DOC, IS 5.9.0

**Comment by gomathyk** [comment]
Please remove the pagewise TOCs, since we have the right menu that has the same content now.
