### ISSUE TITLE
Incorrect information in "Multi-factor Authentication using FIDO"

### ISSUE THREAD

**Issue by dewniMW** [wso2/docs-is#578]
In doc [1] the following updates are required.

1- Remove the information on feature availability with 4955 WUM update for WSO2 IS 5.7.0 as it is irrelevant for 5.9.0 doc space. The configuration information given under this section should also be removed.

2- Add the following toml configurations.

[fido.trusted]
origins=["https://localhost:9443"]

[1] https://is.docs.wso2.com/en/5.9.0/learn/multi-factor-authentication-using-fido/

**Comment by YvonneW** [comment]
The content will be updated with https://github.com/wso2/docs-is/pull/588.
