### ISSUE TITLE
Subheading are not displayed when the right menu link is clicked

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#581]
## **Description:**
Navigate to a page (Eg: [1]). Then you can see the right side navigation plane which links to the subheadings that page. Now click on one link. Notice that even though you are navigated to that specific content, the page does not show the heading title. To see the heading title you need to scroll up. This needs to be fixed.

[1] -  https://is.docs.wso2.com/en/5.9.0/setup/installation-prerequisites/

## **Suggested Labels:**
DOC, IS 5.9.0, IS 5.10.0

**Comment by gomathyk** [comment]
This is resolved with https://github.com/wso2/docs-is/pull/1060
