### ISSUE TITLE
Adding an example image

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#586]
**Description:**
In the doc [1] following text appears inside an info block.

```
When the Management Console Sign-in page appears, the web browser will typically 
display an "insecure connection" message, which requires your confirmation before 
you can continue.
```
When reading this section, the above text is bit confusing. Is it possible to insert an image here?

[1] - https://is.docs.wso2.com/en/5.9.0/setup/running-the-product/

**Suggested Labels:**
IMPROVEMENT, DOC, IS 5.9.0, IS 5.10.0

**Comment by gomathyk** [comment]
Closing this issue following a discussion, since this is a general behavior and need no further explanation.
