### ISSUE TITLE
Missing link in migration doc

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#626]
**Description:**
On page [1] under the topic [2], the following text appears. 
```
WSO2 Identity Server supports scope validation when issuing tokens for 
OAuth Service Providers
```
In the above text, `OAuth Service Providers` part should have a link but its missing. Therefore, the corresponding page should be linked.

[1] - https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/
[2] - https://is.docs.wso2.com/en/5.9.0/setup/migrating-what-has-changed/#scope-validation-for-token-issuing

**Suggested Labels:**
DOC, IS 5.9.0, IS 5.10.0

**Comment by YvonneW** [comment]
This will get fixed with https://github.com/wso2/docs-is/pull/634
