### ISSUE TITLE
No documentation for new OIDC claim mapping

### ISSUE THREAD

**Issue by dineshjweerakkody** [wso2/docs-is#677]
**Description:**
There is no documentation around how to map custom claims to OIDC scope. Steps could be found in the following blog post [1].

[1] https://medium.com/identity-beyond-borders/handling-custom-claims-with-openid-connect-in-wso2-identity-server-56d3b6e4319b

**Affected Product Version:**
IS Doc 5.7.0 and later

**Comment by ayshsandu** [comment]
Fixed 5.9.0 upward in https://github.com/wso2/docs-is/pull/913
