### ISSUE TITLE
Need to add one step in twilio SMS OTP configuration

### ISSUE THREAD

**Issue by nilasini** [wso2/docs-is#678]
**Description:**

Need to add the following step in \[1] under "Configuring the identity provider"->step10->Click here to configure Twilio as the service provider.->(c)

**Get Twilio Phone Number to send the SMS**

You will need a Twilio-enabled phone number (a phone number purchased through Twilio) to send SMS using Twilio.

After signing up for your trial account, navigate to the Phone Numbers page in your console. You’ll see the phone number that we’ve selected for you: note the phone number’s capabilities, such as Voice, SMS, and MMS.

![1](https://user-images.githubusercontent.com/20336761/67743177-ef890d00-fa43-11e9-9499-771aea0c3706.png)

![2](https://user-images.githubusercontent.com/20336761/67743180-f021a380-fa43-11e9-96ca-a8d719273750.png)

Get your first Twilio phone number and keep that as the "FROM_NUM" in your HTTP Payload \[2]

More details can be found in \[3]

\[1] https://is.docs.wso2.com/en/5.9.0/learn/configuring-sms-otp/
\[2] https://www.twilio.com/docs/usage/tutorials/how-to-use-your-free-trial-account
\[3] https://is.docs.wso2.com/en/5.9.0/learn/configuring-sms-otp/

**Comment by sherenewso2** [comment]
Fixed with https://github.com/wso2/docs-is/pull/683
