### ISSUE TITLE
Doc Feedback: Broken download link to saml2-web-app-pickup-manager.war

### ISSUE THREAD

**Issue by ishara-p** [wso2/docs-is#706]
Location : https://is.docs.wso2.com/en/5.9.0/learn/configuring-single-sign-on/

In the Setting up section, "Download the saml2-web-app-pickup-dispatch.war and saml2-web-app-pickup-manager.war and deploy them in Tomcat."

Download link for saml2-web-app-pickup-manager.war is not working. User is unable to download the webapp from here.

**Comment by ishara-p** [comment]
![image](https://user-images.githubusercontent.com/1682467/68180225-e676cf00-ff60-11e9-80c6-5fe430683686.png)

**Comment by ayshsandu** [comment]
Fixed in the latest documents.
