### ISSUE TITLE
Doc Feedback: correct the pickup dispatch/manager app urls as http://localhost:8080 

### ISSUE THREAD

**Issue by ishara-p** [wso2/docs-is#707]
Location : https://is.docs.wso2.com/en/5.9.0/learn/configuring-single-sign-on/

Please correct the app urls as http://localhost:8080 in the two sections given below.

Try it out
Navigate to http://localhost.com:8080/saml2-web-app-pickup-dispatch.com on your browser and click Login.

Now, if you navigate to http://localhost.com:8080/saml2-web-app-pickup-manager.com and click

**Comment by gomathyk** [comment]
The docs recommend using localhost.com now. Since these URLs work, closing this issue.
