### ISSUE TITLE
JWT Grant details need to be added

### ISSUE THREAD

**Issue by darshanasbg** [wso2/docs-is#762]
Have JWT Grant details in https://is.docs.wso2.com/en/5.9.0/learn/oauth-2.0-grant-types/ and any other appropriate place.

**Comment by darshanasbg** [comment]
Can refer: https://www.google.com/url?q=https://medium.com/@piraveenaparalogarajah/try-out-jwt-bearer-grant-with-wso2-identity-server-d384b3c30579 for details.

**Comment by YvonneW** [comment]
https://github.com/wso2/docs-is/pull/937 will reflect the changes.
