### ISSUE TITLE
[Clustering] RDMS should be RDBMS

### ISSUE THREAD

**Issue by isharailanga** [wso2/docs-is#769]
**Description:**
![image](https://user-images.githubusercontent.com/14251853/68281603-0cee5480-009e-11ea-9ace-0432e43e3b5a.png)

I guess this should be correct as RDBMS.

**Suggested Assignees:**
@sherenewso2 @YvonneW @gomathyk 

**Affected Product Version:**
IS 580 and all the doc spaces

**Comment by gomathyk** [comment]
Fixed from 540 to 580.
