### ISSUE TITLE
Doc Feedback: Upgrade details are missing

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#802]
Location : https://is.docs.wso2.com/en/5.9.0/setup/upgrading-from-an-older-version-of-wso2-is/

The page is empty

**Comment by ayshsandu** [comment]
Hi @ajanthan, going forward there will not be separate documentation for migrating from older versions. Migrating from the immediate previous version and any older version is covered in the same [migration process](https://is.docs.wso2.com/en/5.9.0/setup/migration-process/) guide in a unified wad.
