### ISSUE TITLE
Doc Feedback: Monitoring Logs - Page not found

### ISSUE THREAD

**Issue by nilushancosta** [wso2/docs-is#832]
Location : https://is.docs.wso2.com/en/5.9.0/administer/configuring-hazelcast/

The "Monitoring Logs" link (https://is.docs.wso2.com/en/5.9.0/administer/monitoring-logs) shows a page not found error

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/867
