### ISSUE TITLE
Doc Feedback: Additional information required regarding clustering configuration

### ISSUE THREAD

**Issue by nilushancosta** [wso2/docs-is#833]
Location : https://is.docs.wso2.com/en/5.9.0/administer/configuring-hazelcast/

1. Configuring hazelcast.properties when using the deployment.toml file
The document asks the user to configure the <IS_HOME>/repository/conf/hazelcast.properties file with the configurations given in the document.

However the hazelcast.properties file displays a warning as follows inside it.
"WARNING: Don't edit the file manually unless you are not using the deployment.toml file." This is due to IS 5.9.0 using a deployment.toml file as a single point for all configurations.

Therefore it is better to add an explanation on how to configure the hazelcast.properties file when using the deployment.toml file or add a link to a document explaining how its done.

2. Clustering configurations in axis2.xml file
The last paragraph states that some configurations may be needed in the <IS_HOME>/repository/conf/axis2/axis2.xml file. It is better to explain how to configure it or add a link to a document explaining how its done.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/867
