### ISSUE TITLE
Some config related to userstore need to be documented according to new config model.

### ISSUE THREAD

**Issue by piraveena** [wso2/docs-is#838]
1. In this doc [1], we have SCIMEnabled property with **""**

```
[user_store.properties]
"SCIMEnabled" = true
```
But the correct config, should not contain "". It should be as 
```
[user_store.properties]
SCIMEnabled = true
```
Even though both can work, the recommended way is to use without ""

Moving [user_store]config related issue to a new git issue https://github.com/wso2/docs-is/issues/844

**Comment by gomathyk** [comment]
Have resolved along with https://github.com/wso2/docs-is/issues/844
