### ISSUE TITLE
Remove Embedded LDAP related configurations

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/docs-is#846]
**Description:**
User should not change embedded LDAP related configurations. So remove the instructions in documentation[1] and other places to disable the embedded LDAP. 

[1] - https://is.docs.wso2.com/en/5.9.0/setup/configuring-the-primary-user-store

**Suggested Labels:**

- config

**Affected Product Version:**

- 5.9.0

**Related Issues:**
- https://github.com/wso2/product-is/issues/6896

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/867
