### ISSUE TITLE
The SAML artifact resolve request given the doc gives NPE error

### ISSUE THREAD

**Issue by piraveena** [wso2/docs-is#858]
The SAML artifact resolve request given in these two docs [1][2], give Null Pointer Error when executing. We have to modify the doc. Need to change  **<Artifact> as <samlp:Artifact>**

SAML artifact resolve request should be changed as below. 

```
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body>
        <samlp:ArtifactResolve
            xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
            xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
            ID="_6c3a4f8b9c2d" Version="2.0"
            IssueInstant="2004-01-21T19:00:49Z">
            <Issuer>https://ServiceProvider.com/SAML</Issuer>
            <samlp:Artifact>
                AAQAADWNEw5VT47wcO4zX/iEzMmFQvGknDfws2ZtqSGdkNSbsW1cmVR0bzU=
            </samlp:Artifact>
        </samlp:ArtifactResolve>
    </SOAP-ENV:Body>


```

[1]https://docs.wso2.com/display/IS570/Configuring+SAML+2.0+Artifact+Binding
[2]https://docs.wso2.com/display/IS580/Configuring+SAML+2.0+Artifact+Binding

**Comment by sherenewso2** [comment]
Updated 5.7.0 and 5.8.0 [1] and sent a PR for 5.9.0 docs [2] 

[1] https://docs.wso2.com/display/IS570/Configuring+SAML+2.0+Artifact+Binding
[2] https://github.com/wso2/docs-is/pull/859/files

**Comment by piraveena** [comment]
@sherenewso2 , in the previous comment, </SOAP-ENV:Envelope> is missing in the request. Please find the correct one below. 

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <samlp:ArtifactResolve xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_6c3a4f8b9c2d" Version="2.0" IssueInstant="2004-01-21T19:00:49Z">
         <Issuer>https://ServiceProvider.com/SAML</Issuer>
         <samlp:Artifact>AAQAADWNEw5VT47wcO4zX/iEzMmFQvGknDfws2ZtqSGdkNSbsW1cmVR0bzU=</samlp:Artifact>
      </samlp:ArtifactResolve>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by sherenewso2** [comment]
Ack. Fixed it with https://github.com/wso2/docs-is/pull/873
