### ISSUE TITLE
[Improvement ] Provide brief summary for why we should paste " org.wso2.carbon.identity.sample.extension.authenticators-5.7.0.jar " inside the <IS_HOME>/repository/components/dropins directory

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#869]
**Description:**
There is no any information why we should paste that jar inside <IS_HOME>/repository/components/dropins directory

Document: Configuring a Service Provider for Adaptive Authentication
https://is.docs.wso2.com/en/5.9.0/learn/configuring-a-service-provider-for-adaptive-authentication/

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/949
