### ISSUE TITLE
Images and information should be updated- "Managing Consent Purposes" document

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#891]
Affected IS version: wso2IS 5.9.0  

The current documents contained the oldest images with less information.
But in the current implementation, there are some additional features are added, So we need to update the document content to align with the current implementation.

Document: "Managing Consent Purposes" - https://is.docs.wso2.com/en/5.9.0/learn/managing-consent-purposes/

**Comment by gomathyk** [comment]
Added new screenshots, and descriptions for the two new fields. 

Will be resolved with https://github.com/wso2/docs-is/pull/977/files
