### ISSUE TITLE
Latest IS docs are still refering to playground app instead of pickup app

### ISSUE THREAD

**Issue by piraveena** [wso2/docs-is#910]
Latest IS docs are still refering to playground app instead of pickup app. The samples need to be changed in the docs[1,2]

https://is.docs.wso2.com/en/5.9.0/learn/basic-client-profile-with-playground/
https://docs.wso2.com/display/IS580/OAuth+2.0+with+WSO2+Playground

**Comment by sherenewso2** [comment]
AFAIK, these functionality are not available in the OAuth Pickup app yet. Therefore, closing this issue.
