### ISSUE TITLE
"Reference" Section need a brefing

### ISSUE THREAD

**Issue by ayshsandu** [wso2/docs-is#914]
When clicking on "Reference" in the top navigations, it directs the user to https://is.docs.wso2.com/en/5.9.0/references/default-ports-of-wso2-products/ page, which is not very good UX. 

Landing page should be brief some context information of the reference section.

![reference](https://user-images.githubusercontent.com/5061791/69945363-674cca80-150f-11ea-80e9-27c95b91fb3c.png)

Other sections also can be improved.

**Comment by sherenewso2** [comment]
Fixed with https://github.com/wso2/docs-is/pull/955
