### ISSUE TITLE
Update SAML query profile documentation with the new flow

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/docs-is#924]
**Description:**
Since the testing sample was moved to sample-is with [https://github.com/wso2/samples-is/pull/211](https://github.com/wso2/samples-is/pull/211) which includes minor changes including the process of overriding the flow mentioned in the current documentation. This needs to be updated with the new flow ASAP.

**Suggested Assignees:**
@deshankoswatte

**Comment by ayshsandu** [comment]
Please update https://is.docs.wso2.com/en/5.9.0/learn/querying-saml-assertions/ as well

**Comment by deshankoswatte** [comment]
Hi @ayshsandu,

> Please update https://is.docs.wso2.com/en/5.9.0/learn/querying-saml-assertions/ as well

This is updated with the changes
