### ISSUE TITLE
Spelling mistake in User Account Associations API definition section

### ISSUE THREAD

**Issue by brionmario** [wso2/docs-is#935]
`authenticated` is spelled `auhtentiated` in user account association API definition section [1].

[1] https://is.docs.wso2.com/en/next/develop/association-rest-api/#/me/delete_me_associations

<img width="1052" alt="Screen Shot 2019-12-04 at 5 39 59 PM" src="https://user-images.githubusercontent.com/25959096/70141552-488c3680-16bd-11ea-8e99-aa69faa21b2c.png">

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/939
