### ISSUE TITLE
Links in MFA sample in Quick Start Guide don't work

### ISSUE THREAD

**Issue by mifanc** [wso2/docs-is#936]
**Description:**
Following links are 404 in the QS page under MFA at https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/

1. https://is.docs.wso2.com/en/5.9.0/assets/attachments/org.wso2.carbon.identity.sample.extension.authenticators-5.7.0.jar
2. https://is.docs.wso2.com/en/5.9.0/assets/attachments/sample-auth.war

**Suggested Labels:**

404

**Suggested Assignees:**

**Affected Product Version:**
5.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/ MFA section:
https://is.docs.wso2.com/en/5.9.0/assets/attachments/org.wso2.carbon.identity.sample.extension.authenticators-5.7.0.jar
https://is.docs.wso2.com/en/5.9.0/assets/attachments/sample-auth.war

**Related Issues:**

**Comment by ayshsandu** [comment]
Hi @mifanc,

We have fixed this issue recently with https://github.com/wso2/docs-is/issues/923.
Now the `org.wso2.carbon.identity.sample.extension.authenticators-5.9.0.jar` and `sample-auth.war` contains the latest released artefacts compatible for IS-5.9.0. 

Can you please try with new artefacts in the document.
