### ISSUE TITLE
Missing document for Terminating User Sessions in IS-5.9.0

### ISSUE THREAD

**Issue by ayshsandu** [wso2/docs-is#957]
Need to get the content on how to use end-user dashboard to terminate user sessions from https://medium.com/@pamodaaw/user-session-management-service-in-wso2-is-5-9-0-3e2a613c26c8 to https://is.docs.wso2.com/en/5.9.0/learn/using-the-end-user-dashboard/

**Comment by gomathyk** [comment]
Will be resolved with https://github.com/wso2/docs-is/pull/1020/.
