### ISSUE TITLE
Wrong version name in the IS installation location

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#959]
Location : https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/

OS | Home Directory
-- | --
Mac OS | /Library/WSO2/IdentityServer/5.7.0
Windows | C:\Program Files\WSO2\IdentityServer\5.7.0
Ubuntu | /usr/lib/wso2/IdentityServer/5.7.0
CentOS | /usr/lib64/IdentityServer/5.4.70

Rather than hardcoding the version number in the doc, try to find a way to dynamically generate based on product version.

**Comment by ayshsandu** [comment]
Hi @ajanthan,

Thanks for reporting this. We have fixed this in https://github.com/wso2/docs-is/pull/954. Changes will be reflected in a while in the live site.
