### ISSUE TITLE
Unused <TOMCAT_HOME> directory

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#960]
Location : https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/

The "Steps to configure and run the samples" mentions <TOMCAT_HOME> but it is never used subsequently. I guess it should be changed  <IS_SAMPLE_DISTR> as it is mentioned without properly introducing it.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/962
