### ISSUE TITLE
Non-obvious sample down instruction

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#961]
Location : https://is.docs.wso2.com/en/5.9.0/get-started/quick-start-guide/

The "Steps to configure and run the samples" mentions a GitHub page and asks to download "samples" but the page has so many files. It is better to mention the exact file name/pattern to point the sample distribution.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/docs-is/pull/962
