### ISSUE TITLE
Userstore configuration properties are confusing

### ISSUE THREAD

**Issue by janakamarasena** [wso2/docs-is#966]
In the doc "Properties used in Read-write LDAP user store manager"[1]
[1] - https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-read-write-ldap-user-store/#properties-used-in-read-write-ldap-user-store-manager

In the given property table It is unclear what should be used as the property key in the deployment.toml file.

**Comment by gomathyk** [comment]
A note has been added to https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-read-write-ldap-user-store/#properties-used-in-read-write-ldap-user-store-manager mentioning what each column should be used for. 
Will be resolved with https://github.com/wso2/docs-is/pull/969.
