### ISSUE TITLE
Incorrect configurations in SMSOTP when using Nexmo

### ISSUE THREAD

**Issue by darshanasbg** [wso2/docs-is#981]
SMS URL defined in the Nexmo section should be changed from,
`https://rest.nexmo.com/sms/json?api_key=&api_secret=&from=NEXMO&to=ctx.num&text=ctx.msg`
to
`
https://rest.nexmo.com/sms/json?api_key=&api_secret=&from=NEXMO&to=$ctx.num&text=$ctx.msg`

ie. Currently it looks like follows,
<img width="759" alt="Screen Shot 2019-12-15 at 10 55 09 PM" src="https://user-images.githubusercontent.com/1617810/70866338-5334ae80-1f8e-11ea-8d1d-9eace5a92842.png">

once fixed it should looks like follows,
<img width="683" alt="Screen Shot 2019-12-15 at 10 56 16 PM" src="https://user-images.githubusercontent.com/1617810/70866344-752e3100-1f8e-11ea-86f7-f9a1bae3621c.png">

https://github.com/wso2/docs-is/edit/5.9.0/en/docs/learn/configuring-sms-otp.md#L207 already have the '$' in its URL, but it have some issue when rendering the final page. Need to check and fix to not to loose '$' character during the process.

**Comment by gomathyk** [comment]
`https://rest.nexmo.com/sms/json?api_key=&api_secret=&from=NEXMO&to=$ctx.num&text=$ctx.msg`

This is how it appears now.
