### ISSUE TITLE
Config issue in User Self Registration and Account confirmation via Email Channel

### ISSUE THREAD

**Issue by janakamarasena** [wso2/docs-is#990]
```
enable_resolve_notification_channel = true
```

Should be changed

```
resolve_notification_channel = true
```

Doc: https://github.com/wso2/docs-is/blob/master/en/docs/learn/multi-channel-self-registration-and-account-confirmation.md

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/991
